### DISCUSSION TITLE
A command to pre-locate elements for react-native

### DISCUSSION THREAD

**Discussion by booker-dragon** [mobile-dev-inc/Maestro#1441] [Ideas]
I would like to suggest a new feature/command to pre-locate views with id
Most of the time, the view tree hierarchy is huge for react native, for each tap action, it will loop through the tree to locate the element.

If a command is available to pre-locate all the needed elements for a screen, it could make the flow running much faster

For example
```
- locateViews:
    id: ["viewA", "viewB"...]
- tapOn:
    id: "viewA"
```
