### DISCUSSION TITLE
Is it possible to use a dynamic file path on a runScript action?

### DISCUSSION THREAD

**Discussion by jbarriojim** [mobile-dev-inc/Maestro#1442] [Q&A] [answered]
Hi,

I'm trying to pass the language of the APP to the maestro execution with a parameter to load the strings for the clicks or the assertions. The same application could have different languages.

My tries started focused on passing a dynamic value in the runScript action. I tried multiple things but it is not working. I can see the path that I want if I print it but it is not transformed when I use it in the file parameter.

Some of my tries:

```
appId: ${APPID}
env:
  filePath: /languages/${LANG}.js
---
- evalScript: ${console.log(filePath)}

# (0) Load language
- runScript:
    file: filePath
```
```
file: ${filePath}
file: ${env.filePath}
file: ${String(filePath)}
```

EXTRA INFO:
The filePath constant is solved properly at the evalScript clause.
_/languages/en.js_

Is any way to pass the file parameter a dynamic file path?

**Comment by simon-gilmurray** [comment]
Can you try:

`filePath: ${"/languages/" + LANG + ".js"}`

**Reply by jbarriojim** [reply]
Thank you for your fast answer, but unfortunately is not working.
![imagen](https://github.com/mobile-dev-inc/maestro/assets/24703132/997c5466-5529-4d0c-addb-0e31c60dce0b)

It seems that the value is not resolved and is taken as a constant value.

**Reply by simon-gilmurray** [reply, marked as answer]
Hmm this might be an issue with the way you're trying to load it within the env at the start of the file, or it might be that runFlow doesn't like the JS parameter

Perhaps you can achieve this within the flow with something like this? (I haven't tested):

```
- evalScript: ${output.setLanguage = "/languages/" + LANG + ".js"}
- runScript:
    file: ${output.setLanguage}
```

If this doesn't work, then I'd be tempted to call out to a separate flow that has conditionals that loads the correct language file based on the parameter you've passed in, e.g.:

```
- runScript:
    when:
      true: ${LANG == 'Spanish'}
    file: /languages/spanish.js
- runScript:
    when:
      true: ${LANG == 'French'}
    file: /languages/french.js
```
