### DISCUSSION TITLE
How to make End to End testing suite for different Personas and run them one after the other

### DISCUSSION THREAD

**Discussion by AyushVatsalScaler** [mobile-dev-inc/Maestro#1648] [Q&A]
Suppose, 
   - We have different User Personas A, B , C 
   - We have different features X, Y, Z
   - Each feature has many different flows M, N, P

Now, 
   - For user persona A, B, C , we use all features X, Y, Z
   - But, for different Personas (A, B, C), for the same feature( let's say X) , we have some common flows (M) and some unique flows like (flow N inside feature X is unique to Persona B ,  flow P inside feature X is unique to Persona C , and we have flow M , which is common for all Personals (A, B, C) for feature X)

How, do we make end to end Test Suite for this scenario, such that, first we execute all test cases for Persona A, then for Persona B and then for Persona C .
Currently, the test cases structure is such as below:
          - TestSuite Folder
          ----config.yaml
          ----(Feature)X
          --------(flow) M
          --------(flow) N
          --------(flow) P
          ----(Feature)Y
          --------(flow) Q
          --------(flow) R
          ----(Feature)Z
          --------(flow) S
          --------(flow) T

**Comment by portyu9** [comment]
Hi @AyushVatsalScaler 

A good structure is to make each persona an orchestrating Flow and move shared behavior into reusable `runFlow` subflows.

For local execution, you can explicitly order the personas in `config.yaml`:

```yaml
executionOrder:
  continueOnFailure: false
  flowsOrder:
    - persona_a
    - persona_b
    - persona_c
```

Each persona flow can then call whatever common and persona-specific subflows it needs.

For example:

```yaml
# persona_a.yaml
appId: com.example
---
- runFlow: shared/login.yaml
- runFlow: persona-a/create-order.yaml
- runFlow: shared/logout.yaml
```

One important limitation: `executionOrder` is **local-only** and does not apply to Maestro Cloud.

If strict sequencing is required in Cloud because later scenarios genuinely depend on earlier ones, put the dependent sequence into a single top-level orchestrator Flow (using `runFlow`), or sequence separate Cloud executions from CI.

Where possible, keep top-level tests independently runnable; that gives you much better isolation and parallelism.

Please mark this answer as accepted if it helped, thank you.
