### DISCUSSION TITLE
How to create a swipe action script when the element is at the top of the page?

### DISCUSSION THREAD

**Discussion by tarunaairasia** [mobile-dev-inc/Maestro#1725] [Q&A]
Hi everyone,

When the element is at the top of the page, how can I actually get the device to swipe correctly?
Since I'm currently learning Maestro, I would welcome any advice.
I'm grateful in ahead!

![image](https://github.com/mobile-dev-inc/maestro/assets/154976008/8c8ffd84-7146-4a2c-b0bc-9ed5f7e1eb15)

**Comment by portyu9** [comment]
Hi @tarunaairasia 

If the goal is to **scroll the page**, you generally don't need to start the swipe from the element at the very top.

Use a normal directional swipe:

```yaml
- swipe:
    direction: UP
```

or percentages if you need tighter control:

```yaml
- swipe:
    start: 50%, 80%
    end: 50%, 20%
```

If the actual goal is to reveal another element, `scrollUntilVisible` is usually preferable to manually choosing swipe coordinates.

Current Maestro also supports starting a swipe from a specific point within an element:

```yaml
- swipe:
    from:
      text: "Desired element"
      point: "50%,85%"
    direction: UP
```

That can help when the center of a large element isn't a suitable gesture origin.

I couldn't inspect the screenshot attached to the original post because the GitHub attachment is no longer retrievable through the available URL, so I can't tell which of these best matches the exact UI shown there.

Please mark this answer as accepted if it helped, thank you.
