### DISCUSSION TITLE
Can we have the device name in the flow?

### DISCUSSION THREAD

**Discussion by dimzeta** [mobile-dev-inc/Maestro#2308] [Ideas]
Hello,

First of all thank you for this incredible Framework !

I'm new and I would like to use it to generate some screenshots of my app using multiple simulators at the same time. I do a simple flow just to try it out:

```
# screenshots.yaml

appId: fr.lifeloot.app
---
- launchApp:
    clearState: true
- assertVisible: "Se connecter"
- takeScreenshot:
    path: "test"
- stopApp
```

If I run maestro with multiple devices in parallel, the screenshot is overrided: `maestro test --shard-all 2 maestro/screenshots.yaml`

Is it possible to have something to distinguish the device in the flow? I would like to do something like that:

```
- takeScreenshot:
    path: "test_${DEVICE_NAME}"
```

Or even better with a dynamic folder:
```
- takeScreenshot:
    path: "${DEVICE_NAME}/test"
```

Thank you !
