### DISCUSSION TITLE
tapOn occasionally taps twice?

### DISCUSSION THREAD

**Discussion by abbbe** [mobile-dev-inc/Maestro#2398] [Q&A] [answered]
Figured I ask here before filing a bug report, in case it is a known behavior (and it will be very tricky to create a simple reproducible test case).

So, on the very first screen of my app I have signInAnonButton button, which opens second screen, which has more buttons.
I do tapOn signInAnonButton on the first screen and it works perfectly, bringing me to the second screen, where I press settingsButton button later on. Here is the code
```
- launchApp:
    clearState: true
    arguments:
      mockBleManager: true

# anon login & go to calibration screen
- tapOn:
    id: "signInAnonButton"
- tapOn:
    id: "settingsButton"
```

And a screen recording of normal behavior: https://github.com/user-attachments/assets/c50888ff-01da-40ff-b446-1b73ab03776c

But occasionally, it looks like that tapOn also hits two buttons in succession, once the button on the first screen as it should and another button on the second screen which was never meant to be tapped. Here is the recording of the same script running agains the same app build, on the same simulator:

https://github.com/user-attachments/assets/085a8d68-02a4-479c-bc2e-c6b220bf5624

I figure the issue could be introducing some kind of a delay, but his is ugly. Any clues are appreciated...
