### DISCUSSION TITLE
How to test a slider component with Maestro?

### DISCUSSION THREAD

**Discussion by Melsha-Shanelle** [mobile-dev-inc/Maestro#2424] [Q&A]
I have a slider in my app that lets users select a value. Is there a way in Maestro to simulate moving the slider to a specific value?

For example, I want to test setting it to value 4 or 5
![WhatsApp Image 2025-04-13 at 22 43 44_7d0360fe](https://github.com/user-attachments/assets/808b27ad-5b3d-40de-97f0-47a8b044c136)

**Comment by portyu9** [comment]
Hi @Melsha-Shanelle 

There isn't a dedicated `setSliderValue` command, but you can make this deterministic if the slider supports tapping directly on its track.

For example, for a slider from `1` to `5`, value `4` is 75% across the usable range:

```yaml
- tapOn:
    id: "rating_slider"
    point: "75%,50%"
```

The `point` is relative to the matched element's bounds, so this is much less brittle than using screen coordinates.

In general:

```text
percentage = (target - min) / (max - min) * 100
```

Then assert the resulting value using whatever text/accessibility state your UI exposes.

If your slider only responds to dragging the thumb, current Maestro also supports starting `swipe` from a particular element/point:

```yaml
- swipe:
    from:
      id: "slider_thumb"
      point: "50%,50%"
    direction: RIGHT
```

For an exact numeric target, however, tapping a known position on the track is preferable when the component supports it.

Please mark this answer as accepted if it helped, thank you.
