### ISSUE TITLE
Compose tap on test tag 

### ISSUE THREAD

**Issue by Jparrgam** [mobile-dev-inc/maestro#101]
Hello everyone, is there a way to tap on a compose component with 

``` kotlin
Modifier.testTag("email_test_id")
```
``` yaml
- tapOn:
    optional: false
    id: "email_test_id"
```

result 

![Screen Shot 2022-08-31 at 7 38 43 PM](https://user-images.githubusercontent.com/8985838/187808595-9abf87a4-19fa-4f85-ad9b-f6b9b0a0c58d.png)
