### ISSUE TITLE
[Github Actions] add the option to skip test completion step

### ISSUE THREAD

**Issue by ethanneff** [mobile-dev-inc/maestro#1038]
Waiting for tests to be complete is expensive as I will be using up 2 CI credits (GitHub Actions and Maestro) for a single job. 

Can we have a configuration option to just upload to Maestro Cloud, and not wait for the test response? 

<img width="712" alt="Screen Shot 2023-05-02 at 10 07 27 PM" src="https://user-images.githubusercontent.com/2933593/235836464-ec1a68d1-445b-4417-970e-b3932d4cfd7c.png">

**Comment by axelniklasson** [comment]
Hi there @ethanneff! Yes, you can use the [async mode](https://github.com/mobile-dev-inc/action-maestro-cloud#run-in-async-mode) for this:

```
- uses: mobile-dev-inc/action-maestro-cloud@v1.3.1
  with:
    api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
    app-file: app.zip
    async: true
```
