### ISSUE TITLE
Feature: `defineSelectors` command to support Screen/Page Object design pattern

### ISSUE THREAD

**Issue by larryng** [mobile-dev-inc/maestro#1044]
Additional context in [Slack](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1683300725606219)

I have working locally a command `defineSelectors` intended to help implement the Screen/Page Object pattern. It enables defining custom selectors that you can put in a subflow for loading in test flows. For example:
```yaml
# screens/login.yaml
...
- defineSelectors:
    Login.ForgotPassword: "Forgot password"
    Login.SignIn:
      id: id_sign_in
```

```yaml
# flow.yaml
...
- runFlow: screens/login.yaml  # Load the selectors
- assertVisible:
    selector: Login.ForgotPassword
- tapOn:
    selector: Login.SignIn
```

I'm aware that currently there is a JS approach for doing this, something like:
```js
// screens/login.js
output.Login = {
  ForgotPassword: "Forgot Password",
  SignIn: "id_sign_in"
}
```

```yaml
# flow.yaml
...
- runScript: screens/login.yaml  # Load the selectors
- assertVisible: ${output.Login.ForgotPassword}
- tapOn:
    id: ${output.Login.SignIn}
```

Advantages of `defineSelectors` would be:
 * It's more concise. No need for `output` or `${}`.
 * You can compose multiple selectors.
 * Less leaky. JS approach requires you to know what selector a variable maps to (text, ID, etc.)
 * Better readability.

I'll leave the Disadvantages as an exercise for the reader. 😉 

I can push a PR but would love to gather comments first.

**Comment by simon-gilmurray** [comment]
@larryng Thanks for suggesting this, it looks pretty cool! I was looking for a Page Object Model solution for a while before Maestro added JS integration which made it possible. 

It does read cleaner than having to prefix every element with `${output.` so from that perspective it is an improvement.

**Questions:**

1. Is there any way to improve organisation/readability with your approach? Currently it reads as if it will just be a long list. One current benefit of the JS way is you can group via arrays or nesting e.g. I can reference `${output.cards.allCards.createNewBtn}` using:

```
output.cards = {
    allCardsBtn: 'all_cards_button'

    // All Cards Screen
    allCards: {
        createNewBtn: 'btn_create'
    }
```


2. One thing that would be extremely useful if possible is to provide an id and text to a selector as a combination. I've encountered some screens that have multiple of the same IDs but the text differs. It would be great if we could have something like:

```
- defineSelectors:
       Login.SignIn:
            id: id_sign_in
            text: "Sign in"
```


3. Would be nice if there was an elegant way to add/load them all. Currently I've tried to improve my workflow by having a `loadElements.yaml` that I can call on my tests to load everything in, and then just add my individual element yamls in there so none get missed. I guess I would have the same issue/approach using the proposed solution also.


4. Very minor, but selector is quite a web-based term. Perhaps `element` would be better and more applicable to mobile also?

**Comment by larryng** [comment]
> 1. Is there any way to improve organisation/readability with your approach?

You could group the selectors into separate files: `login.yaml` for `Login` screen selectors, etc.

I'm not sure how nesting would work, particularly when referencing. For example:
```yaml
- tapOn:
    selector: cards.allCards.createNewBtn
```
Would we use the selector with string key `"cards.allCards.createNewBtn"` or the leaf node `createNewBtn` defined in some JSON tree?

> 2. One thing that would be extremely useful if possible is to provide an id and text to a selector as a combination

Yes, that was one of my main motivations and works as you'd expect. You could also use `selector` in combination with other selectors, e.g.:
```yaml
- assertVisible:
    selector: login.sign_in
    enabled: true
```

> 3. Would be nice if there was an elegant way to add/load them all.

My original approach was to define selectors in a workspace and/or flow config, but that goes against Maestro's (implicit?) design philosophy, which is that flows should be self-contained except for env vars.

> 4. Very minor, but selector is quite a web-based term. Perhaps element would be better and more applicable to mobile also?

I'm reluctant to add more terminology, though I do feel "selector" is overloaded here. I think more precisely we're defining a named set of selectors, so maybe `defineSelectorSets` and `selectorSet` is more appropriate naming. I'll defer to the Maestro devs here.
