### ISSUE TITLE
Allow to define default launch arguments

### ISSUE THREAD

**Issue by retyui** [mobile-dev-inc/maestro#1046]
I face with annoying thing that I have to define `arguments` in each test flow (contestant values, won't be changed)

```yaml
- launchApp:
    appId: "com.example.app"
    arguments: 
       isMaestro: true
       turnOffAnalytical: true
```

Will be great to have ability to define a default launch arguments in `config.yaml` that will be used all the time by `launchApp` command
