### ISSUE TITLE
Add ability to fail a test run using command

### ISSUE THREAD

**Issue by retyui** [mobile-dev-inc/maestro#1047]
I need to throw an error based on my conditions

for example:
```yaml
- evalScript: ${output.myStatus = 'unknown'} # success / fail / timeout
- repeat: 
    while:
      true: ${output.myStatus === 'unknown'}
    commands:
      # my complicated logic (waitFor error or success ) 
      # `success` can be different, depends on feature flags

- runFlow:
    when:
      true: ${output.myStatus !== 'success'}
    commands:
      - throwError: "Booking finished with status: ${output.myStatus}"
      # ^^^ my imaginary command (example only) 
```
