### ISSUE TITLE
[v1.27.0] `inputText` failing on `secureTextEntry`

### ISSUE THREAD

**Issue by KrisLau** [mobile-dev-inc/maestro#1061]
**Describe the bug**
`inputText` failing on `secureTextEntry`. The Input is showing a  "Strong Password" message and text entry just becomes disabled

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro test` with `- inputText: 'whatever"` on a secure text entry Input
3. The Flow fails at the text input

**Expected behavior**
Enter the password

**Screenshots**
![image](https://github.com/mobile-dev-inc/maestro/assets/46275463/e86f57f7-d2a8-4f97-b609-2c52a4eae5f8)

**Environment information (please complete the following information):**

- Maestro version: v1.27.0
- Platform: iOS 16.2
- Device model and OS version: iPhone 11
- Simulator
- Host: Mac Mini

**Workspace (if applicable)**
N/A

**Bug report output (if applicable)**
N/A

**Additional context**
N/A

**Comment by filipgerat** [comment]
Facing the same issue. Android does not suffer from this. It also doesn't help to set the secureTextEntry property to false

**Comment by andrejguran** [comment]
I have the same issue and can't get through login/signup step

**Comment by heba-mekawi** [comment]
Same here, any recommendation to fix it please ?

**Comment by orbiteleven** [comment]
It's not great, but as a workaround I'm setting those fields to be normal text fields when I detect I'm in testing mode.

**Comment by thalmann-christof** [comment]
As a workaround, you could disable auto-filling in your simulator.
_Inside your simulator: Settings → Passwords → Type in a random password → Password options → Disable toggle_

In Maestro Cloud, it seems to be disabled by default, so there are no issues there.

**Comment by KrisLau** [comment]
@axelniklasson

**Comment by solidcell** [comment]
For anyone else running into this, I have two solutions:

Maestro
```
- swipe:
    direction: RIGHT
- tapOn: "Settings"
# ^^ that could probably be done via some command to open Settings.app's app ID
- tapOn: "Passwords"
- inputText: "a" # anything works here as the password
- pressKey: Enter
- tapOn: "Password Options"
- runFlow:
    when:
      visible: "1" # Only toggle when currently ON. This isn't great, but I don't know of a way to be more explicit about which toggle it is. Luckily, there's just the one (for now...)
    commands:
      - tapOn: "AutoFill Passwords"
```

That's obviously not great.

However, here's how you can do it via the CLI beforehand:

`plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO /Users/jesse/Library/Developer/CoreSimulator/Devices/5CF9D7C1-293E-4EB7-8FAB-B0B9A083B4DB/data/Library/UserConfigurationProfiles/EffectiveUserSettings.plist`

Replace your simulator's device ID of course. Way better.

**Comment by imjn** [comment]
Hi 👋🏽  Any updates on this issue? I'm facing the same issue.

> However, here's how you can do it via the CLI beforehand:

> plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO /Users/jesse/Library/Developer/CoreSimulator/Devices/5CF9D7C1-293E-4EB7-8FAB-B0B9A083B4DB/data/Library/UserConfigurationProfiles/EffectiveUserSettings.plist

↑ For my case, just this command didn't solve the issue but running this command ↓ too solved it.

`plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO ~/Library/Developer/CoreSimulator/Devices/YOUR_DEVICE_ID/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/UserSettings.plist`

**Comment by horaczech** [comment]
I managed to get it working with specifying the text in env variable and then using the variable:
```
appId:  someId
env:
  PASSWORD: "111111"
---

- tapOn:
    id: "inputId"
- inputText: ${PASSWORD}
```
