### ISSUE TITLE
Incorrect InputText on iOS : ""

### ISSUE THREAD

**Issue by g123k** [mobile-dev-inc/maestro#109]
Hello,

Here is my flow:

```yaml
appId: com.apple.MobileAddressBook
---
- launchApp
- tapOn: "John Appleseed"
- tapOn: "Modifier"
- tapOn: "Ajouter un numéro"
- inputText: 123123
- tapOn: "OK"
```

And running it on a French simulator gives `""` instead of `123123`:

https://user-images.githubusercontent.com/246838/187998322-7de8264a-bd2c-44a4-82db-819af13712e2.mp4
