### ISSUE TITLE
[Feature Request] app id as a condition

### ISSUE THREAD

**Issue by chilikasha** [mobile-dev-inc/Maestro#1105]
hi,

I'd like to make a test(s) for a bunch of apps which are almost identical and could differ a bit in some logic or UI.
I've checked the docs: https://maestro.mobile.dev/advanced/conditions#conditions and I see it's not possible to pass app id as a condition. could you please consider adding that if it's doable?

please see example below:

**Describe the solution you'd like**
```yaml
- runFlow:
    when:
      appId: com.example.app
    commands:
      - tapOn: someBtn
```

**Comment by stephenduong12** [comment]
Any idea for that, I got the same issue. There is a bunch of cases need to filter by condition before taking action

**Comment by Fishbowler** [comment]
You can do this with the existing `true` parameter.
If you've got a flow that is used with multiple appId's, you're already parameterising some stuff. You could do something like this:

```
appId: ${APP_ID}
---
- launchApp
- runFlow:
    when:
      true: ${APP_ID == "com.app1"
    commands:
      - tapOn: "App1 Login"
- runFlow:
    when:
      true: ${APP_ID == "com.app2"
    commands:
      - tapOn: "App2 Login"
```

I'm gonna call this closed, but shout if I'm wrong.
