### ISSUE TITLE
[Feature Request] Add the ability to mark variables as "secret"

### ISSUE THREAD

**Issue by ShawInnes** [mobile-dev-inc/Maestro#1122]
**Is your feature request related to a problem? Please describe.**

I would like the ability to mark a step or variable as secure/sensitive and not show the value in the log. 

Currently the following is logged at the start of a test run (values are not displayed(, however as the run progresses the variables are replaced with the actual values.  

![image](https://github.com/mobile-dev-inc/maestro/assets/610688/b6286d5b-bcb6-4ac9-a857-d237a9798877)

**Describe the solution you'd like**

The ability to configure whether a particular step should be logged fully, or have the values obscured.

```
- tapOn:
    id: "email_address"
- inputText:
    text: ${MAESTRO_EMAIL}
    secure: true
- tapOn: "Continue"
```

**Describe alternatives you've considered**

Alternatively, hiding variable substitution for variables with specific name could be considered.  Eg. "SECURE_EMAIL" but this feels bit obscure.

**Additional context**

I'd be keen to submit a PR for this feature, but I started looking at the codebase and I couldn't work it out - If you could point me in the general direction I'd be happy to give it a go.  (I'm an experienced developer, just not in the java ecosystem)

**Comment by Fishbowler** [comment]
I think this might be solved with the label functionality?

**Comment by Fishbowler** [comment]
Example:
```
- tapOn: 'Password'
- inputText:
    text: "secret thing"
    label: 'Enter the password'
```
