### ISSUE TITLE
Implement retry strategy

### ISSUE THREAD

**Issue by testableapple** [mobile-dev-inc/Maestro#1124]
**Is your feature request related to a problem? Please describe.**
Most of the frameworks allow us to retry failed tests. Maestro currently does not. It would be great to have such an option.

**Describe the solution you'd like**
- Maestro users can set up a `retry-tests-count` in the config file globally or in some flow in particular (similar to `-retry-tests-on-failure` flag in XCTest).
- By default, this count should be equal to `0` (if flow fails, then it fails straight away)
- If a user sets it up (e.g.: `3`) and the flow fails on the first run, then Maestro automatically starts it from scratch, and so on
- These repetitions are clearly displayed in the logs

**Describe alternatives you've considered**
N/A

**Additional context**
Reference: https://twitter.com/testableapple/status/1662915551927193609

**Comment by ubuntudroid** [comment]
This is an essential feature. As the [Maestro Cloud docs](https://cloud.mobile.dev/reference/retries) correctly state:

> The behavior of an application can be complex and challenging to verify, leading to unreliable test results in some instances. This can be caused by various factors such as animations, API calls, backend availability, network interruptions, and temporary outages.

We could for sure just restart the whole test suite ourselves if it fails, but that's far less efficient than just rerunning the failing tests. So a built-in mechanism similar to Maestro Cloud would be much appreciated.

**Comment by abhishekbedi1432** [comment]
We too are this basic feature. Currently we rely on scripts to re-run the test based on its failure status iteratively

**Comment by Fishbowler** [comment]
Inherently, we dislike global retries, the same way we dislike hard waits.
We appreciate that there's a middle-ground though, for stuff outside the app's control, like flaky server infrastructure.
A couple of months back, we added this: https://docs.maestro.dev/api-reference/commands/retry

**Comment by Fishbowler** [comment]
Of course, if you really want to, you can do something horrid like:

```
- retry:
    maxRetries: 3
    commands:
      - runFlow: myTest.yaml
```

But hopefully, it'll be something much nicer like:

```
- retry:
    maxRetries: 3
    commands:
      - runScript: createUserViaAPI.js
      - tapOn: 'login'
      - tapOn: 'username'
      - inputText: 'test_user'
      - tapOn: 'password'
      - inputText: 'test_password'
      - tapOn: 'Log In'
      - assertVisible: 'Your Account'
- tapOn: 'Product List'
- tapOn; 'Add to Cart'
- tapOn: 'Checkout'
```
