### ISSUE TITLE
[Feature Request] JUnit improvement: Specify name and classname per flow and customize testsuite name

### ISSUE THREAD

**Issue by Dambakk** [mobile-dev-inc/maestro#1127]
**Is your feature request related to a problem? Please describe.**
Our tools for handling junit reports uses testsuite name, testcase classname and testcase name from the reports. It would be nice to be able to set these from our flows. Currently maestro only supports one testsuite tag, and each testcase has the same id, name, and classname. 

**Describe the solution you'd like**
We would like to declare fields that should appear in the junit report for each flow. Example flow:

```
appId: ${APP_ID}
name: Become customer
className: Profile
testsuite: Authentication
env:
  CLEAR_LAUNCH: true
  ENVIRONMENT: prod
  LOGIN: false
tags:
  - testrail
---
- runFlow: ../setup.yaml
```
