### ISSUE TITLE
"Below" not working on app settings

### ISSUE THREAD

**Issue by g123k** [mobile-dev-inc/maestro#113]
Hello,

Here is my flow:

```yaml
appId: com.android.settings
---
- launchApp
- tapOn: 
    below:
        text: "Apps"
```

Below or event Above keywords don't work in the Android app settings (Android 12).
Maestro selects the first element of the list instead.

Here is a video:

https://user-images.githubusercontent.com/246838/188229790-80084ba0-c83f-45fa-9fa0-6019114fef95.mp4
