### ISSUE TITLE
Scrolling fails in React Native app on iOS.

### ISSUE THREAD

**Issue by RhyG** [mobile-dev-inc/Maestro#1135]
**Describe the bug**
Any scroll commands fail on React Native + iOS, causing tests to fail. This includes `scroll`, `scrollUntilVisible` and `swipe`. This effectively makes Maestro unusable for us on iOS. Works fine on Android however. From some tests it seems it works fine on `1.25.0` but not on later versions.

Similar was reported [here](https://github.com/mobile-dev-inc/maestro/issues/1037) however the solution there unfortunately didn't work in our case (removing a layer of nesting from the navigation) and isn't really an option.

Keen to find out if this has been experienced by anyone else, or if it's a known issue. Any help or suggestions are appreciated, because otherwise Maestro has been great but this is a big blocker.

**To Reproduce**
Currently working on a minimal repro, but so far haven't been able to produce one. Will update the report as soon as that's done.

**Expected behavior**
Scroll commands work on iOS.

**Screenshots**
Hard to demonstrate via screenshot, but on the left is a list of 25 elements, and the test has the following step:
```yaml
- swipe:
    direction: UP
- scrollUntilVisible:
    element:
      text: 'Item 24'
```
Both of these are failing, as shown by the list still being at the top and not having scrolled to `Item 24`.
![screeny](https://github.com/mobile-dev-inc/maestro/assets/47733004/ff0e9dce-87b5-481c-89ad-923374107aa3)
Identifying sections have been blacked out.

**Environment information (please complete the following information):**

- Maestro version: 1.28.0
- Platform: iOS
- Framework: React Native
- Simulator
- Host: all

**Comment by amanjeetsingh150** [comment]
Hey @RhyG can you attach all the logs in the following directory?

```
~/Library/Logs/maestro
```

**Comment by RhyG** [comment]
> Hey @RhyG can you attach all the logs in the following directory?
> 
> ```
> ~/Library/Logs/maestro
> ```
> 
> Also if possible can you share the sample app where this is reproducible?

Currently working on a repro as this repo belongs to my company behind a private repo, will post a repro as soon as I can get one. 🙏

**Comment by dwightdhooge** [comment]
Having the same here on certain screens in react-native. Scroll & swipe marks as completed, but nothing seems to happen. 

nothing special in the logs

**Comment by samuelgja** [comment]
Same issue here. Swipe command is marked as done, but nothing happens.
`scrollUntilVisible` not working.

**Comment by amanjeetsingh150** [comment]
Hey @RhyG were you able to repro this in sample app. I need to validate one of the potential solutions. 

@samuelgja @dwightdhooge can you share the maestro flow and app binary where this is happening?

**Comment by RhyG** [comment]
> Hey @RhyG were you able to repro this in sample app. I need to validate one of the potential solutions.
> 
> @samuelgja @dwightdhooge can you share the maestro flow and app binary where this is happening?

Hey sorry for the late reply, unfortunately no luck and haven't had time to continue working on it.

**Comment by plrdev** [comment]
I upgraded from 1.26 to 1.32 and this started happening for me too. I have a test that scrolls our flatlist and it passes on iOS, but the list doesn't move at all. On Android, swipe seems to still work properly.

**Comment by amanjeetsingh150** [comment]
Hey @plrdev can you share you flow and binary where this is reproducible and other details like is it react native or native?

**Comment by plrdev** [comment]
Unfortunately the app is a private one, so I cannot share it, but the flow is:

```
---
- launchApp
- waitForAnimationToEnd:
    timeout: 5000
- assertVisible:
    id: 'articlesList'
- swipe:
    start: 300, 800
    end: 300, 0
    duration: 100
- swipe:
    start: 300, 800
    end: 300, 0
    duration: 100
```

So two swipes to scroll downwards in a flatlist. It was working before on iOS and still works on Android.

**Comment by amanjeetsingh150** [comment]
Hey @plrdev thanks for sharing can you replicate the flatlist in different app. Would need more data to reproduce this issue.

**Comment by skam22** [comment]
Seeing the same issue, I have an onboarding screen with 6 different pages.  The sample onboarding flow does not work:

```yaml
appId: org.wikimedia.wikipedia
---
- launchApp
- repeat:
    times: 6
    commands:
      - swipe:
          direction: LEFT
          duration: 400
      - waitForAnimationToEnd
- tapOn: Get started

```

The problem is that the first swipe is firing but the screen itself does not move (simulator is not receiving the input).  The swipe test, however, passes... but the tapOn test fails because the "Get Started" button is not visible.
