### ISSUE TITLE
[Feature Request] Infinite scrolling

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1145]
**Is your feature request related to a problem? Please describe.**

I would like to make sure that given an app view with many scrollable elements it does so.

So I thought of using something like this:

```
- scrollUntilVisible:
    element:
      id: "viewId"
    direction: DOWN
    timeout: 50000
    speed: 40
    visibilityPercentage: 100
```

or

```
- scrollUntilVisible:
    element:
      id: "viewId"
    direction: DOWN
```

Since there is no element called `viewId` it should detach indefinitely, but it doesn't, after a while the operation terminates which fails.

I tried on the twitter app, looking for a word like keyword `#android`, then run the following codes, the ones above.

But it doesn't go well.

<img width="836" alt="Screenshot 2023-06-12 alle 20 29 20" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/49ad15dc-32ca-43d4-b1bb-b8e728dab56f">
