### ISSUE TITLE
Blob assertion returns different values than tapOn

### ISSUE THREAD

**Issue by raulriera** [mobile-dev-inc/maestro#1155]
**Describe the bug**

Using blob to assert views seems to produce different results when using the same regex for `tapOn`. Take these 3 rows for example

```yaml
- assertVisible: "Peter Validator 0.00272 SOL Activating -"
- assertVisible: "Peter Validator 0.00272 SOL Active -"
- assertVisible: "Peter Validator 0.00272 SOL Inactive -"
```

Trying to difference them we are using these blob

```yaml
- tapOn: ".*Inactive.*"
```

Strangely the above only works for Activating, when using inactive it will tap on a row with "Active"

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro test ...`
3. The Flow fails at tapping the correct view, it will correctly assert that it exists (I assume so)

**Expected behavior**
It should tap the correct "inactive" row

**Screenshots**
<img width="372" alt="Screenshot 2023-06-14 at 3 58 09 PM" src="https://github.com/mobile-dev-inc/maestro/assets/24159/52a8c8b2-3ef6-454b-a5db-5ccd699ac850">

**Workspace (if applicable)**
https://console.mobile.dev/uploads/e896dce6-912b-4d08-b990-b1d99e2d67e5?benchmark=bcdcd76c-f702-4f71-b605-bb30545ccd33&teamId=6bfb2940-2d02-4c2b-bbc6-86d94cf44654&analysisId=a6c173c0-d58b-4db5-8cb7-c15fcd0acaf9&appId=f6316059-ac78-48f0-8610-a3bf0291b217

That workspace won't fail at the specific place, but you can see the whole flow there
