### ISSUE TITLE
Maestro keeps tapping the wrong row

### ISSUE THREAD

**Issue by raulriera** [mobile-dev-inc/maestro#1168]
**Describe the bug**
It seems that maestro can't handle screens with a lot of similar content. Its failing to tap the correct row even tho the text is clearly different

```yaml
env:
  ACTIVE_ACCOUNT: "Peter Validator 0.00272 SOL Active.*"
  ACTIVATING_ACCOUNT: "Peter Validator 0.00272 SOL Activating.*"
  INACTIVE_ACCOUNT: "Peter Validator 0.00272 SOL Inactive.*"

# more content

- runFlow:
    when:
      visible: ${{ACTIVE_ACCOUNT}}
    commands:
      - tapOn:
          text: ${{ACTIVE_ACCOUNT}} # BUG 🐛: it will tap the Inactive row for some reason
          index: 0
```

**To Reproduce**
Unsure what is special about these screen, I believe its just that the hierarchy is a lot of the same

```json
"children":[{"attributes":{"accessibilityText":"Peter Validator 0.00272 SOL Active - Peter Validator 0.00272 SOL Inactive - Peter Validator 0.00272 SOL Inactive - Peter Validator 0.00272 SOL Inactive - Peter Validator 0.00272 SOL Inactive - Peter Validator 0.

... etc
```

**Expected behavior**
It should tap the correct flow, in the debug and maestro studio the values can be clearly seen as different

**Screenshots**
Strangely for the following image, it keeps tapping on the wrong rows
<img src="https://github.com/mobile-dev-inc/maestro/assets/24159/2c493800-d3b1-4f31-8d35-5fd242359c4d" width=250 />

**Environment information (please complete the following information):**

This is happening locally and maestro cloud

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

[debug.zip](https://github.com/mobile-dev-inc/maestro/files/11779563/debug.zip)
