### ISSUE TITLE
[Feature Request] Creating groups/steps in a single flow

### ISSUE THREAD

**Issue by matheusdf6** [mobile-dev-inc/maestro#1181]
I miss the possibility of giving semantic context to certain steps of my tests. I usually use comments in my code as a workaround, but they are only useful if someone is reading the files.

```yaml
# Close alert
- assertVisible: Balance is outdated
- tapOn: Ok!

# Find the correct card in carrousel
- repeat:
    while:
      notVisible: "Options of card ${output.env.testCardType}"
    commands:
      - swipe:
          start: 80%, 25%
          end: 10%, 25%

# Go to My Card Screen
- tapOn: "My Card"
```
I could create multiple files to separate these steps, but as the main project grows and new tests are added, the test project could become very large and difficult to organize.

So instead of that, we could use a sintax like this:
```yaml
- group:
    name:  Close alert
    commands:
        - assertVisible: Balance is outdated
        - tapOn: Ok!

- group:
    name:  Find the correct card in carrousel
    commands:
        - repeat:
            while:
              notVisible: "Options of card ${output.env.testCardType}"
            commands:
              - swipe:
                  start: 80%, 25%
                  end: 10%, 25%

- group:
    name:  Go to My Card Screen
    commands:
        - repeat:
            while:
                notVisible: "Options of card ${output.env.testCardType}"
            commands:
                - tapOn: "My Card"
```
With this syntax, outputs can become clearer for non-developers and provide labels in their own language.
