### ISSUE TITLE
[Maestro v1.2.9] Notification permission not being set on ios simulator

### ISSUE THREAD

**Issue by otoniel-isidoro** [mobile-dev-inc/maestro#1223]
**Describe the bug**
I can't set Notification permissions for iOS simulators.

I'd expect to set it as such:
```
appId: ${APP_ID || 'my.app.id'}
---
- launchApp:
    appId: "${APP_ID}"
    clearState: true
    stopApp: true
    permissions: { notifications: allow }
```
The app has some navigation logic that shows the notifications permission screen if it is not set yet, but by setting the permissions with Maestro the screen should not show up, and it is working on Android but on iOS it is ignoring the permissions set on the launchApp command.

Looking at the Maestro code I couldn't get why the notifications permission is not listed [here](https://github.com/mobile-dev-inc/maestro/blob/8aacc071649fe0b5eb755d6fe92ea115245d1a63/maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt#L345C5-L345C5)?

Would really appreciate any help you can give, and happy to share more info as required!

Thanks,

Toni

**Environment information:**

- Maestro version v1.2.9
- Platform: iOS 16.4
- Framework: React Native
- Device model and OS version: iPhone
- Simulator, emulator or physical device: Simulator
- Host: Mac M1
