### ISSUE TITLE
[Feature Request] WireMock

### ISSUE THREAD

**Issue by timrijckaert** [mobile-dev-inc/maestro#1250]
**Is your feature request related to a problem? Please describe.**
I wish to use WireMock in my Maestro test flows.  
My test flows would first configure the responses before starting the app.
This can be done by using the Admin API that WireMock offers and Maestro's [HTTP Request support](https://maestro.mobile.dev/advanced/javascript/make-http-s-requests)

Therefore I wish to use the `onFlowStart` and `onFlowComplete` commands to run arbitrary scripts

**flow.yaml**
```yaml
appId: ${APPID}
onFlowStart:
- runScript: 'start-wiremock.sh'
- runScript: "perform-http-requests-to-wiremock-to-change-stubbing.js"
onFlowComplete:
- runScript: 'stop-wiremock.sh'
---
- ...
```

I would stop my WireMock which each run so stubs are reset to defaults.
Currently I have no way of doing this.  

**Describe the solution you'd like**
`runScript` and/or `onFlowStart` and a new `onFlowFinally` should be introduced where arbitrary shell scripts can be executed.  
The `onFlowFinally` would be executed even when the test fails, similar to any `finally` block in other programming languages.  

**Additional context**
Similar to #247
