### ISSUE TITLE
[1.30.4] Regex matcher is parsed on each parameter pass to flow

### ISSUE THREAD

**Issue by LukaszCuler** [mobile-dev-inc/maestro#1300]
**Describe the bug**
It looks the regex used for text matcher is parsed on each parameter pass to flow, so its backslashes need additional escaping. Let's use a simple `at-least-one-letter-or-number` matcher:
`(\w|\s)+`

If we use it directly, it will work in the proper form `(\w|\s)+`, if we want to pass it once, we'd need to use `(\\w|\\s)+`, two times - `(\\\\w|\\\\s)+`

**To Reproduce**
This can be reproduced easily even on the menu screen with the sample given below. `regex_first.yaml` should be launched.

*regex_first.yaml*
```
appId: ""
---
- assertVisible: (\w|\s)+
- runFlow:
    file: "regex_check.yaml"
    env:
      rgx: (\\w|\\s)+
- runFlow:
    file: "regex_check_flow_in_middle.yaml"
    env:
      rgxMid: (\\\\w|\\\\s)+
```

*regex_check_flow_in_middle.yaml*
```
appId: ""
---
- runFlow:
    file: "regex_check.yaml"
    env:
      rgx: ${rgxMid}
```

*regex_check.yaml*
```
appId: ""
---
- assertVisible: ${rgx}
```

**Expected behavior**
It would be good to parse regex only when actually using it as a matcher, and drop parsing on passing as an argument.

**Environment information (please complete the following information):**

- Maestro version: [1.30.4]
- Platform: [Android 13]
- Framework: [Native Android]
- Device model and OS version: Android Emulator based on Android 13
- Host: Mac M1
