### ISSUE TITLE
[Feature] Extend `launchApp` to allow permissions

### ISSUE THREAD

**Issue by wadey1** [mobile-dev-inc/maestro#133]
eg:
```
- launchApp:
      clearState: true
      permissions: { notifications: 'YES', location: 'always' }
```

**Comment by dmitry-zaitsev** [comment]
For now, our recommended approach is to use optional commands to handle that:

```
# Tap on Allow on permission dialogue if one shows up
- tapOn:
     text: Allow
     optional: true
```
