### ISSUE TITLE
[Maestro cloud] Cloud failed to recognize a special character

### ISSUE THREAD

**Issue by dtirafaelsouza** [mobile-dev-inc/maestro#1341]
Hi guys, do you know if the text '&' is recognized by the maestro cloud?

I tryed to run a test on the maestro cloud, utilizing an internationalization library, but the test that I send failed to recognize this text 'TERMS & CONDITIONS'. When I run the same test on my machine, the flow works perfectly.

```
appId: ${APP_ID}
---
- launchApp:
    clearState: true
- runScript:
    file: 'dictionary.js'
    env:
      appId: ${APP_ID}
# TC 4820 - Opening the app for the first time
- assertVisible:
    id: 'terms-title'
    text: ${output.dictionary.txtTermsAndConditions}
- assertVisible:
    id: 'terms-subtitle'
    text: ${output.dictionary.txtTermsAndConditionsSubtitle}
- assertVisible:
    id: 'terms-scrollview'
- assertVisible:
    id: 'button-disabled'
```

The maestro cloud have some limitation to recognize some characters?

<img width="1072" alt="Captura de Tela 2023-08-11 às 14 35 08" src="https://github.com/mobile-dev-inc/maestro/assets/136634689/3d73ab4f-7894-44be-b1ae-c2d16e56aa1c">

<img width="1177" alt="Captura de Tela 2023-08-11 às 14 43 57" src="https://github.com/mobile-dev-inc/maestro/assets/136634689/120a5474-23c8-4d83-a0c4-574a96a2b59a">

<img width="492" alt="Captura de Tela 2023-08-11 às 14 45 30" src="https://github.com/mobile-dev-inc/maestro/assets/136634689/58a9730f-7306-4715-ba63-1d6d6eb79bac">
