### ISSUE TITLE
[v1.31.0] runFlow environment modifying outer environment

### ISSUE THREAD

**Issue by nathanalderson** [mobile-dev-inc/maestro#1352]
**Describe the bug**
When using `runFlow` with the `env` key, the values in the nested `env` are modifying the values in the calling environment.

**To Reproduce**
Run the following test with `maestro test`:

```yaml
appId: ""
env:
  VAR1: "original val"
---
- runFlow:
    env:
      VAR1: "nested val"
    commands:
      - evalScript: ""
- evalScript: "${console.log('outer VAR1: ' + VAR1)}"
```

Observe the logged message `outer VAR1: nested val`, which should read `outer VAR1: original val`.

**Expected behavior**
The `env` provided to `runFlow` should only affect that flow, not the calling environment.

**Screenshots**
n/a

**Environment information (please complete the following information):**

- Maestro version: 1.31.0. Note that this behavior did not happen on 1.27.0.
- Platform: n/a
- Framework: n/a
- Device model and OS version: n/a
- Simulator, emulator or physical device: n/a
- Host: Linux

**Workspace (if applicable)**
See minimal reproduction test above which has no dependencies on a device or browser.

**Bugreport output (if applicable)**
[2023-08-15_141215.zip](https://github.com/mobile-dev-inc/maestro/files/12352349/2023-08-15_141215.zip)
[2023-08-15_141228.zip](https://github.com/mobile-dev-inc/maestro/files/12352350/2023-08-15_141228.zip)

**Additional context**
n/a
