### ISSUE TITLE
[Feature Request] Platform conditions at the step-level

### ISSUE THREAD

**Issue by btrautmann** [mobile-dev-inc/maestro#1353]
**Is your feature request related to a problem? Please describe.**

I'd love if I could write platform conditionals at the _step_ level. I see that it can be done at the _flow_ level thanks to https://github.com/mobile-dev-inc/maestro/pull/1007, but this is often not granular enough. One case I've run into is when tapping a button to share some content from an application. The "share" view that comes up is platform-dependent, and I'd like to be able to assert that the expected view is there depending on the current host platform.

This was actually suggested [here](https://github.com/mobile-dev-inc/maestro/issues/302#issuecomment-1335236364) in the issue that the above PR resolved, but it doesn't look like that suggestion was implemented. I'm wondering if it's something that should be reconsidered.

**Describe the solution you'd like**

I imagine a syntax similar to what was written for `runFlow`:

```yaml
- assertVisible:
  when:
    platform: android
  text: "Apps List"
- assertVisible:
  when:
    platform: ios
  text: "Copy"
```

**Describe alternatives you've considered**

The most direct workaround is likely to use the `runFlow` conditional, but this requires creating a new flow file for each platform that may only be used in this one place. The helper is also decoupled from the root flow file (the one that calls it) which may lead to confusion and in the worst case, could be deleted and the mistake not realized until the next running of the root flow.

```yaml
- runFlow:
    when:
      platform: android
    file: share_helper_android.yaml # has a single step that verifiers "Apps  List" is visible
- runFlow:
    when:
      platform: android
    file: share_helper_ios.yaml # has a single step that verifiers "Copy" is visible
```

**Additional context**
N/A

**Comment by Fishbowler** [comment]
It's not quite what you're after, but here's an intermediate workaround that prevents having to split into multiple files

```
- runFlow:
    when:
      platform: Android
    commands:
      - assertVisible:
          text: "Apps List"

- runFlow:
    when:
      platform: iOS
    commands:
      - assertVisible:
          text: "Copy"
```

**Comment by L-Weisz** [comment]
@Fishbowler I have the same issue, I would like to be able to directly write something like 
```
- runFlow:
    when:
      platform: Android
    repeat:
      while:
      notVisible:
        id: "continue_with_Email"
      commands:
        - back
```

but I have this error Failed to parse file:
Unrecognized field "repeat" (class maestro.orchestra.yaml.YamlRunFlow), not marked as ignorable

**Comment by Fishbowler** [comment]
In your case, the structure should be more like this:

```
- runFlow:
    when:
      platform: Android
    commands:
      - repeat:
          while:
            notVisible:
              id: "continue_with_Email"
          commands:
            - back
```

Repeat and runFlow are similar in that both take a list of commands (or in runFlow's case, it can take a file instead).

Docs for repeat: https://maestro.mobile.dev/api-reference/commands/repeat
