### ISSUE TITLE
how to clear input field?

### ISSUE THREAD

**Issue by Shlyankin** [mobile-dev-inc/maestro#137]
I want to clear the text field and input a new value.

Double tap "emulating" for text selection does not work because it has a delay
```
- tapOn: "http.*"
- tapOn: "http.*"
```
Flow:
```
appId: com.delivery.boy.fl
---
- launchApp
- tapOn:
    id: ".*button_menu"
- tapOn: "Server Address"
# want to select text and replace it
- tapOn: "http.*"
- tapOn: "http.*"
- inputText: "http://url:80/"
# want to select text and replace it
- tapOn: "ok"
- back
- back
- tapOn: "Login"
- inputText: "p1"
- tapOn: "Password"
- inputText: "0000"
- tapOn: 
    id: ".*button_login"
```

How can i do this? Thanks in advance for your reply.
