### ISSUE TITLE
[Feature Request] Enable ADB-Like Direct URL Opening in App Functionality for ﻿openLink

### ISSUE THREAD

**Issue by langtind** [mobile-dev-inc/maestro#1397]
With ADB, it's possible to open URLs directly with the app, even when the URLs are not verified.

```
adb shell am start -a android.intent.action.VIEW -d "https://www.company.com/invitation/c77ca9d0-5ff7-4b59-8d1b-4802b054e9cd" com.company.android.maestro.debug
```

This request is to extend the functionality of `openLink` to replicate this behavior.

**Describe the solution you'd like**

Add a property (e.g., `openWithViewIntent`) to `openLink` that allows opening the URL in the same way as ADB does:

```yaml
-  openLink:
    link: https://www.company.com/invitation/c77ca9d0-5ff7-4b59-8d1b-4802b054e9cd
    autoVerify: true
    openWithViewIntent: true
```

**Describe alternatives you've considered**

An alternative solution currently is to add steps in your flow to add the URLs to the "Open by default" list. However, this approach increases the runtime of the flow and may be more fragile.

```yaml
# Adding company.com and www.company.com as supported links on Android
-  runFlow:
    when:
      platform: Android
    commands:
      - launchApp: "com.android.settings"
      - tapOn: "Apps"
      - tapOn: "All apps"
      - scrollUntilVisible:
          element:
            text: "App Name"
      - tapOn: "App Name"
      - scrollUntilVisible:
          element:
            text: "Open by default"
      - tapOn: "Open by default"
      - tapOn: "Add link"
      - tapOn: "company.com"
      - tapOn: "www.company.com"
      - tapOn: "Add"

-  openLink:
    link: https://www.company.com/invitation/c77ca9d0-5ff7-4b59-8d1b-4802b054e9cd
    autoVerify: true
```

**Additional context**

Discussion on Slack: [Slack Discussion](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1693299687056699)
