### ISSUE TITLE
[Feature Request] Dynamic paths can be used under the file runScript parameter 

### ISSUE THREAD

**Issue by jbarriojim** [mobile-dev-inc/maestro#1446]
**Is your feature request related to a problem? Please describe.**
When I try to use a variable at the file runScript parameter, the variable is not transformed. The variable is used as a literal in spite of use the value of the variable.

In example this code, the evalScript is printing the filePath variable value but the runScript is going to raise an error (the path _.maestro/languages${LANG}.js Flow file is invalid_):

```
env:
  filePath: /languages/${LANG}.js
---
- evalScript: ${console.log(filePath)}

- runScript:
    file: ${filePath}
```

**Describe the solution you'd like**
The string  passed as file parameter should transform the variables using their values.

**Describe alternatives you've considered**
You can see many of them in this discussion
https://github.com/mobile-dev-inc/maestro/discussions/1442
