### ISSUE TITLE
[v1.32.0] `launchApp` command affecting iOS simulator's ability to retrieve current location

### ISSUE THREAD

**Issue by ricardopereira** [mobile-dev-inc/Maestro#1458]
I've been experiencing an issue with the `launchApp` command in Maestro UI Tests tool, which leads to a malfunction in the iOS simulator's ability to obtain its current location.

**Steps to reproduce:**

1. Manually set a custom location in the iOS Simulator using the path: iOS Simulator > Features > Location > Custom location.
2. Launch an app, like Apple Maps, and verify the correct location is shown.
3. Use the Maestro flow with the following commands:
```yaml
- launchApp:
    clearState: false
    clearKeychain: false
    permissions:
      location: inuse
      usertracking: allow
      notifications: allow
```
4. Launch the same app (or another one) and observe that the simulator fails to retrieve the current location.

**Additional observations:**

- When attempting the same with Apple Maps using the flow:
```yaml
appId: com.apple.Maps
---
- launchApp:
    clearState: false
    clearKeychain: false
- tapOn:
    id: "UserLocationButton"
```
I received a location error (screenshot attached: Simulator Screenshot - iPhone 14 Pro - 2023-09-14 at 12.53.53.png).

![Simulator Screenshot - iPhone 14 Pro - 2023-09-14 at 12 53 53](https://github.com/mobile-dev-inc/maestro/assets/3541185/3265ce34-8188-4365-b555-d2d45d008686)

I tried both manually setting the location and using the `setLocation` command from Maestro ([setLocation reference](https://maestro.mobile.dev/api-reference/commands/setlocation)), but the issue persisted.

It seems that there might be an underlying issue with how the `launchApp` command or possibly the `idb-companion` interacts with the simulator's location services.

**Expected behavior**
`launchApp` command not interfering with the ability to retrieve current location in the iOS simulator and, in consequence, be able to set different locations while running tests.

**Environment information (please complete the following information):**

- Maestro version: v1.32.0 (⚠️  but I faced this issue in other Maestro versions)
- Platform: iOS 16.4 and iOS 17
- Framework: Native iOS
- Device model and OS version: iPhone 14 Pro with iOS 16.4 or iOS 17
- Simulator
- Host: MacBook Pro M1 with macOS Ventura 13.5.1 (22G90)

**Bugreport output**

 - [2023-09-19_113823.zip](https://github.com/mobile-dev-inc/maestro/files/12658830/2023-09-19_113823.zip)
 - [xctest_runner_2023-09-19_113759.log](https://github.com/mobile-dev-inc/maestro/files/12658831/xctest_runner_2023-09-19_113759.log)

**Attachments**

 - Screen Recording: https://github.com/mobile-dev-inc/maestro/assets/3541185/7658ec1e-1fb9-4146-81a2-df6cecb6e2df

Thank you for looking into this ❤️
