### ISSUE TITLE
Pass different, platform-specific `appId`s in a single flow

### ISSUE THREAD

**Issue by bartekpacia** [mobile-dev-inc/maestro#1472]
### Use case

My app is cross-platform, and its UI and accessibility labels are almost 100% the same across Android and iOS. The only thing that differs is the application ID (Android) and bundle ID (iOS), for historical reasons.

I'd like to be able to run the same flow on both platforms easily. Currently I have to change the `appId` manually inside the flow, or [pass appId as env var](https://maestro.mobile.dev/troubleshooting/frequently-asked-questions), or split my single flow into 3 flows: 2 platform-specific flows and 1 common flow, containing all the test steps.

I think each of these solutions add a bit too much friction for something so basic.

### Proposal

```yaml
appId:
  android: pl.baftek.discoverrudy
  ios: pl.baftek.discoverRudy
---
- clearState
- launchApp
- tapOn: Increment
# ...
```
