### ISSUE TITLE
Multiple Selectors At The Same Time [v1.3.3]

### ISSUE THREAD

**Issue by satbirkira** [mobile-dev-inc/maestro#1508]
**Describe the bug**
Multiple selectors will be ignored. 

**To Reproduce**

```
- runFlow:
    when:
      visible:
        id: "fnctst-checkbox-agree"
        checked: false
    commands:
        - ....
```

This also causes a "Assertion is false: id: fnctst-checkbox-agree is visible" which does not make sense
```
- assertVisible:
    id: "fnctst-checkbox-agree"
    checked: true
```

**Expected behavior**
What should happen is that if "fnctst-checkbox-agree" is not checked, then the commands should run, but the commands will run regardless of the checked state. The second snippet, it thinks it's doing a assertNotVisible or something

Note: This checkbox is using BouncyCheckbox from "react-native-bouncy-checkbox",

**Comment by satbirkira** [comment]
I figured it out! Here is what I had to do, kind of weird but it works.

`
- runFlow:
    when:
      visible:
        id: "fnctst-checkbox-agree"
        text: "checked"
    commands:
        - ....
`

`
- assertVisible:
    id: "fnctst-checkbox-agree"
    text: "checked"
`

**Comment by rob4226** [comment]
It would be really nice to have multiple selectors logically `AND`'d together, especially `id` and `text`.

For example, I want to check that my login button displays the text `'login'`.  Currently, I can `assert: "login"` but there are other places on the page that also have the text `'login'` so I have to specify `index: 1` which makes the test brittle because the order or number of items containing the text in question could change.

By having `id` `AND` `text` the assertion below would say: 
**Assert that the element with `id` `'loginBtn'` contains the text `'login'`**
 
```yaml
- assertVisible:
    id: "loginBtn"
    text: "login"
```

Currently, this also passes but I wish it would fail:

```yaml
- assertVisible:
    id: "loginBtn"
    text: "Some non-matching text"
```
