### ISSUE TITLE
[Feature Request] setLocation to accept external env variables

### ISSUE THREAD

**Issue by elcaptain** [mobile-dev-inc/maestro#1536]
**Is your feature request related to a problem? Please describe.**
Right now `setLocation` does not accept external env variables.

file.yaml:
```
appId: xxx
---
- launchApp
- waitForAnimationToEnd
- setLocation:
    latitude: ${lat}
    longitude: ${long}
``` 
run:
`maestro test -e lat=52.390568 long=-2.587910 file.yaml`

error:
`Cannot deserialize value of type `double` from String "${lat}": not a valid `double` value (as String to convert)`

**Describe the solution you'd like**
I'd like `setLocation` to accept external env variables.

**Describe alternatives you've considered**
I've tried wrapping the number in quotes but it did nothing: `maestro test -e lat='52.390568' long='-2.587910' file.yaml`
