### ISSUE TITLE
Swipe with variables to start and end command

### ISSUE THREAD

**Issue by rafaelsoncineduobox** [mobile-dev-inc/maestro#1551]
**Describe the bug**
It is not possible to pass variables to the start and end of the swipe

**To Reproduce**
```
appId: br.com.test
env:
  END_X: 90%
  START_X: 10%
  HEIGHT: 90%
---
- swipe:
    start: ${START_X}, ${HEIGHT}
    end: ${END_X}, ${HEIGHT}
```

Failed to parse file: path/main.yaml                                                              
For input string: "${START_X}"

**Expected behavior**
I hope the maestro interprets it as follows

```
- swipe:
    start: 10%, 90%
    end: 90%, 90%
```
**Screenshots**

**Environment information (please complete the following information):**

- Maestro version 1.32.0
- Platform: Android/iOS
- Framework: React Native
- Device model and OS version: [Pixel 6, iPhone 13 ios 15.5]
- Simulator, emulator
- Host [Linux Ubuntu]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**
