### ISSUE TITLE
[Feature Request] Copy text to clipboard and paste in a text field

### ISSUE THREAD

**Issue by pulakdp** [mobile-dev-inc/maestro#1565]
I'd like to re-create pasting to a text field from clipboard. Currently, I have a text with me that I want to input in a text field but since the text is long and using `inputText`, it starts to type it in character by character. There is `pasteText` but there's no `copyText` parameter to take text from the script itself. Adding this will be helpful as it opens up more possibilities involving javascript.

I'm looking to achieve something like the following:

```
appId: com.example.app
---
- launchApp
- copyText:
    text: "Some text"
- tapOn:
    id: "searchFieldId"
- pasteText
```

I couldn't find any way of achieving this in the docs. Let me know if there are any ways to achieve this currently or if there are plans to introduce something like this. Thanks.
