### ISSUE TITLE
[v1.34.0] Android/iOS execution order not running flows in the correct flow order when a flow is used multiple times in the config.yaml

### ISSUE THREAD

**Issue by DavidREntwistle** [mobile-dev-inc/maestro#1567]
**Describe the bug**
When running the flow folder on Android, the flow execution order is now not running the flows in correct order listed in the config.yaml. Within our executionOrder, we reuse a flow file that runs early in the flow and again later. This was previously working in Maestro version 1.33.1. This is not an issue for our iOS flows because there is no repeated flow within the executionOrder. However, this issue does also occur on iOS when a flow is repeated in the executionOrder.

**To Reproduce**
Add multiple of the same flow file's under the executionOrder within the config.yaml file. Run `maestro test main_folder` and observe the flow run order to be incorrect to the listed execution order in the config.yaml file.

**Expected behavior**
When a flow file is repeated within the executionOrder, the executionOrder runs in the correct order. Running the repeated flow file in the correct executionOrder flow order.

**Environment information**
- Maestro version [v1.34.0]
- Platform: [Android/iOS]
- Framework: [Native Android/iOS]
- Device model and OS version: [Pixel 7/iPhone XR]
- Emulator device/Physical Device
- Host [Apple MacBook Pro M2 Max & AWS linux-x86_64]

**Additional context**
This was not an issue on v1.33.1 for Android/iOS.

 E.g:
```
main_folder/
  a_login_folder/
    login_smoke.yaml
  b_home_folder/
    home_smoke.yaml
  c_payments_folder/
    payments_smoke.yaml
  d_utilities _folder/
    enable_screenshots.yaml
```

Our config.yaml file for both Android & iOS then has these in the follow order e.g:
```
executionOrder:
  continueOnFailure: true
  flowsOrder:
     - login_smoke
     - enable_screenshots
     - home_smoke
     - payments_smoke
     - enable_screenshots
```

When running `maestro test main_folder`, the flows are running in the example incorrect order e.g:
```
enable_screenshots
payments_smoke
enable_screenshots
login_smoke
home_smoke
```

**Comment by DavidREntwistle** [comment]
I have rolled back my version to 1.33.1 for now to run the flows in the correct order:
`export MAESTRO_VERSION=1.33.1; curl -Ls "https://get.maestro.mobile.dev/" | bash`

**Comment by DavidREntwistle** [comment]
I have been trying to debug from my side, I believe this issue is caused by a repeated flow within the config.yaml executionOrder. E.g.
```
executionOrder:
  continueOnFailure: true
  flowsOrder:
     - login_smoke
     - enable_screenshots
     - home_smoke
     - payments_smoke
     - enable_screenshots
```

For context, we have an enableScreenshot.yaml file that runs halfway through the execution flow to allow screenshots within our app. When I remove this, the execution flow runs in the correct order like v1.31.1.
