### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ivancantarino** [mobile-dev-inc/maestro#1592]
I haven't found a way to tweak delays between steps.
It would be great to have a `delay` command between steps.

In my case, whenever I ask Maestro do scroll through a page, I would like it to wait until the `tapOn` action is called, for example.
Can I have some hints on how to achieve this?

**Comment by alperefesahin** [comment]
+1

**Comment by clem109** [comment]
+1 on this

We have a specific use case where we need to open up an email to get a magic link, sometimes the email is slow to arrive so we need a way of waiting say 20 seconds then refreshing the page to check if the email is there.

**Comment by shrijanRegmi** [comment]
I use this small hack for creating delays.

```
- tapOn: 
    text: randText  # Any random text that does not exist in the UI
    optional: true  # This should be true so that the test won't fail
    repeat: 2
    delay: 2000
```

**Comment by ngothanhtai** [comment]
> I use this small hack for creating delays.
> 
> ```
> - tapOn: 
>     text: randText  # Any random text that does not exist in the UI
>     optional: true  # This should be true so that the test won't fail
>     repeat: 2
>     delay: 2000
> ```

 using extendedWaitUntil to wait longer, thanks 

```
- extendedWaitUntil: 
     visible: randText  # Any random text that does not exist in the UI
     optional: true  # This should be true so that the test won't fail
     timeout: 60000 // 60 seconds
```

**Comment by BigBlueHat** [comment]
So maybe the new implementation could just provide the following:
```yaml
# FAKE CODE...but wouldn't it be handy?! 😁 
- expendedWaitUntil:
    timeout: 60000 # 60 seconds
```
