### ISSUE TITLE
mutiple condition for when 

### ISSUE THREAD

**Issue by alainib** [mobile-dev-inc/maestro#1619]
hello

is there a way to do multiple when test like a `OR` ?

```
- runScript:
    when:
      visible: Ignorer 
      visible: Se connecter
    file: login.yaml
```   
    
```
- runScript:
    when:
      visible: 'Ignorer' | 'Se connecter'
    file: login.yaml
```

**Comment by simon-gilmurray** [comment]
Yes, you can use a regex OR:

```
- runScript:
    when:
      visible: Ignorer|Se connecter
    file: login.yaml
```

**Comment by alainib** [comment]
how do this with id please ?

like i can have 
` <BarcodeCard testID="codebar"/>` or  `<Qrcode testID="qrcode"/>`. 


this don't work 

- assertVisible:
    id: 'codebar' | 'qrcode'
    
    thanks

**Comment by bartekpacia** [comment]
The following works:

```yaml
appId: com.example.example
---
- launchApp
- tapOn: issue 1619 repro
- runScript:
    when:
      visible:
        text: First|Second
    file: script.js
- runScript:
    when:
      visible:
        id: first|second
    file: script.js

```
