### ISSUE TITLE
[v1.34.1] console output is muted after repeat while with swipe

### ISSUE THREAD

**Issue by camoles** [mobile-dev-inc/maestro#1654]
**Describe the bug**

If we use a snippet of yaml like this on maestro:

```
- repeat:
    while:
        notVisible: "Text we are looking for"
    commands:
        - swipe:
            start: 50%, 70%
            end: 50%, 50%
```

What happens is that the command itself works fine, but maestro stops telling us what it is doing on the console. Any later commands after this are executed, but nothing else is output to the console, not even when the flow finishes.

In case anytone wonders why I am not using scrollUntilVisible instead of this, the reason is that scrollUntilVisible scrolls by swiping from on the upper hafl of the screen, and in my case there is something else there that I do not want to scroll. In my case I have to scroll starting on the lower half of the screen and scrollUntilVisible does not do that.

- Maestro version v1.34.1
- Platform: Android
- Framework: React Native
- Device model and OS version: Android api levels from 26 to 33 (all api levels that this maestro version can run on)
- Emulator and Physical device
- Host: Linux
