### ISSUE TITLE
 Command to install APK or APP files from a URL 

### ISSUE THREAD

**Issue by tian000** [mobile-dev-inc/maestro#1665]
# Feature Request

There should be a command like `installApp` - that allows you to install an APP or APK file from a URL

## Why it is needed

Sometimes you want to test the interaction between different apps - `installApp` would provide a convenient way to install these apps.

Right now I am downloading APKs via Chrome, and I have to toggle a bunch of security settings to get it to work.

**Comment by bartekpacia** [comment]
This sounds like a cool idea to me. Thank you for sharing it with us!

A contribution would be very welcome! :)

---

To clarify a bit more, the scope would be to add new `installApp` command, which accepts either a local path (relative to workspace), or a URL.

```yaml
appId: my.normal.app
---
- installApp:
    path: ./apks/my-additional-app.apk
- installApp:
    url: https://github.com/Albert221/FastShopping/releases/download/v3.0.4/FastShopping.apk
- launchApp
```
