### ISSUE TITLE
[Feature Request] Reusable commands

### ISSUE THREAD

**Issue by lusarz** [mobile-dev-inc/maestro#1673]
**Is your feature request related to a problem? Please describe.**
I'd like to have possibility to define own reusable commands.

**Describe the solution you'd like**
I'd like to have possibility to define custom command (f.e. `commands/fillInput.yaml`) and use it that way:
```
- fillInput
    field: First Name
    value: Maestro
```

**Describe alternatives you've considered**
I'm using combination of env variables and `runFlow` command:
1) `fillInput` command:
```
appId: ${APP_ID}
name: Fill input
tags:
  - re-use
---
- tapOn: ${FIELD}
- eraseText
- eraseText
- inputText: ${VALUE}
```

2) Usage:
```
...
- runFlow:
    file: commands/fillInput.yaml
    env:
      FIELD: First Name
      VALUE: Maestro
- runFlow:
    file: commands/fillInput.yaml
    env:
      FIELD: Last Name
      VALUE: Test
...
```
it works but I'm not happy with the syntax and generated output:

![output](https://github.com/mobile-dev-inc/maestro/assets/10059264/1f13c54c-3afe-47b9-875d-92a1130aa768)
