### ISSUE TITLE
Allow for running Maestro flows that don't have `appId` in frontmatter

### ISSUE THREAD

**Issue by lsaudon** [mobile-dev-inc/maestro#1692]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run maestro tests without specifying an application.

**Describe the solution you'd like**

Be able to either click on the desired application button or launch a link (ex: deep-link).

```yaml
- launch
- openLink:
    link: https://example.com
```

**Comment by harkairt** [comment]
I have the same request.

I would like to write maestro flow tests for features that can be carried out through 2 applications. (even more, 2 different device)

```
# appId: omitted
---
- runFlow: 
    file: a_test.yaml
    udid: a_device
    env:
      APP_ID: ${A_APP_ID}
- runFlow: 
    file: b_t.yaml
    udid: b_device
    env:
      APP_ID: ${B_APP_ID}
````
and
