### ISSUE TITLE
addMedia not showing in Gallery on Android Cloud

### ISSUE THREAD

**Issue by milesingrams** [mobile-dev-inc/maestro#1706]
**Describe the bug**

when using addMedia to add a file it works locally but in the cloud the action succeeds but doesnt show any images in the gallery on Android.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Run on Android Maestro Cloud
2. - addMedia
3. - open gallery

**Expected behavior**
Images should show in gallery after adding media

**Screenshots**
Empty Gallery:
<img width="460" alt="Screen Shot 2024-03-28 at 1 11 43 PM" src="https://github.com/mobile-dev-inc/maestro/assets/4930881/f324bb8b-2408-4c73-8ea2-26ba88682134">

**Environment information (please complete the following information):**

- Maestro version: Cloud
- Platform: Analyzed using Android API level 30
- Framework: Expo v49
- Device model and OS version: Default cloud version of Android
- Simulator, emulator or physical device
- Host: Cloud

**Workspace (if applicable)**
Flow file truncated:

test.yml
```
- addMedia:
    - '../assets/test.png'
- runFlow:
    file: '../shared/select-gallery-image.yml'
```

select-gallery-image.yml:
```
- runFlow:
    when:
      platform: Android
    commands:
      - tapOn:
          id: 'com.google.android.documentsui:id/icon_thumb'
- runFlow:
    when:
      platform: iOS
    commands:
      - tapOn: 'Photo,.*'
```

**Comment by Carl-MONNERA** [comment]
Same for iOS.

I've reported it on the slack and had this response at 05/02/2024:

> unfortunately there is no easy fix here, and will require more time investigating. Since we have a backlog of issues and limited resources I won't be able to give you an ETA, we're sorry for the inconvenience.

In our app, our most used feature is file upload and we cannot test it... it's critical for us and the team seems to ignore this. I'm starting to wonder we're not going to withdraw from the cloud...

**Comment by Hosam-hsm** [comment]
Any update on this?

**Comment by bartekpacia** [comment]
I was not able to reproduce this issue.

**Workspace**

```
$ tree .maestro
.maestro
├── assets
│   └── image.png
├── issue1706.yaml
```

<details><summary>image.png</summary>

Just some random screenshot I had at hand.

![image](https://github.com/user-attachments/assets/791133ad-9538-452b-9ef5-a1132accff5f)

</details> 

**Test flow**

```
appId: com.example.example
name: Issue 1706
---
- launchApp:
    clearState: true
- addMedia:
  - assets/image.png
- launchApp: com.google.android.documentsui
- tapOn: Show roots
- tapOn: Images
- tapOn: Pictures
- assertVisible: image.png
- longPressOn: image.png
- tapOn: Search # wtf?
- tapOn: OK
- assertNotVisible: image.png
```

**Command used to run**

```
$ maestro cloud \                                                                                            exit 130
  --android-api-level 33 \
  build/app/outputs/apk/debug/app-debug.apk \
  .maestro
```

**Recording from Maestro Cloud**

<details><summary>Recording from Maestro cloud</summary>

https://github.com/user-attachments/assets/2c196cdd-4fde-4d71-8fcb-db2fe18a12a8

</details> 


**Environment information**

- macOS 14.5 Sonoma
- Maestro CLI v1.36.0

**Comment by bartekpacia** [comment]
After further investigation, I was still not able to reproduce this problem on all[^1].

It may sound funny, but I believe this is a misunderstanding. The screenshot in the OP shows File Explorer open on the "Recent" tab – but even if the image is added with `addMedia`, it will not show in the "Recent" tab. You have to open that image at least once, only then it'll show in "Recent".

Please see video attached:

https://github.com/user-attachments/assets/b0e49d0e-44b7-4007-884b-55563a7d5b8b

<details><summary>Flow</summary>

```yaml
appId: com.example.example
name: Issue 1706 
---
- launchApp:
    clearState: true
- addMedia:
  - assets/image.png
- launchApp: com.android.documentsui
  # "com.android.documentsui" for API 29 and below
  # "com.google.android.documentsui" for API 30 and above
- tapOn: Show roots
- tapOn: Images
- tapOn: Pictures
- assertVisible: image.png
- longPressOn: image.png
- tapOn: Search # wtf?
- tapOn: OK
- assertNotVisible: image.png
```

</details>

If you experience any more problems with `addMedia`, please create a new issue. This one is not reproducible and I'm going to close it.

[^1] I found that `addMedia` crashed on API 28, but this is a different issue. I created #1821 to track it.
