### ISSUE TITLE
If statement

### ISSUE THREAD

**Issue by ghasemdev** [mobile-dev-inc/maestro#171]
Hi, in my use case, we need to log into the app at first launch, then some other UI test happens. But on the second launch, the login screen doesn't show. In this situation we need an if statement to separate these two work flows.

```yaml
# flow.yaml

appId: com.example.app
---
- launchApp
- if assertVisible : "Phone Number"
  then :
    - tapOn: "Phone Number"
    - inputText: "+123456789"
    - tapOn: "Confirm"
- elif OTHER_CONDITION
  then :
    - ...
- else :
   - tapOn: "Search"
   - ...
- fi
```

**Comment by dmitry-zaitsev** [comment]
To support this particular use case Maestro offers an `initFlow`: https://docs.mobile.dev/reference/app-state-restoration

The idea is that you would extract your login flow into a separate file and refer to it in your actual test

**Comment by dmitry-zaitsev** [comment]
That said, an `if` statement still has its own use cases and we will consider adding it

**Comment by simon-gilmurray** [comment]
+ 1 for this enhancement suggestion, it would be fairly critical in some areas

**Comment by carlonzo** [comment]
Adding a +1 here. we have a similar case where there is a flow (or a set of steps) we would like to run if an element is visible/invisible.

In my mind the ideal syntax would be (recalling similar syntax of the `extendedWaitUntil`):
```yml
- runFlow: open-rh.yml
  visible: Element
  notVisible: Element
```

but I guess the possibility to add elif and/or else would be interesting
