### ISSUE TITLE
when condition to see if element is present on the page by id 

### ISSUE THREAD

**Issue by BogdanZaporojann** [mobile-dev-inc/maestro#1717]
is there any way to use 
when: 
    visible
not by text but by id

**Comment by Fishbowler** [comment]
Yep. Anything Selector-ish is allowed

```
- runFlow:
    when:
      visible: 
        id: my_id
```
