### ISSUE TITLE
Failed to parse file with .yaml during the maestro cloud

### ISSUE THREAD

**Issue by evgenyshenets91** [mobile-dev-inc/maestro#1755]
**Describe the bug**
When I run maestro cloud in remote it failed with an issue:

`Upload request failed (400): Syntax error: Failed to parse file: /./onboarding-process.yaml
Flow file does not exist: jar:file:///tmpFiles/workspaces/workflow810257020248771601.zip!/./generateEmail.js`

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Write any e2e test and add any kind of javascript file
```
# Open Account screen
- tapOn:
    id: 'Customer_Email_input'
- runScript: generateEmail.js
- inputText: ${output.result}
```
2. 'Run `maestro cloud --apiKey $MAESTRO_API_KEY $APP_EXECUTABLE_PATH maestro/onboarding-process.yaml`
4. The Flow fails at executing test

**Expected behavior**
Test should be passed and take js file.

**Environment information (please complete the following information):**

- Maestro Cloud
- Platform: [iOS]
- Framework: [React Native]
- iOS Simulator
- Host [VM template "macos-sonoma-14.4-xcode-15.3" running macOS Sonoma 14.4]

**Workspace (if applicable)**
```
appId: com.XXX.app # need to change to com.fintiba.app if run e2e locally
---
- launchApp
- tapOn:
    id: 'Blocked Account' # Press Basic Product

# Question study reason Screen
- tapOn: 'Yes, I am'

# Calculate blocked amount Screen
- tapOn: 'Continue'

# Customer nationality Screen
- tapOn:
    id: 'Customer_Nationality_input'
- inputText: 'Fran'
- tapOn: 'France'

# Check second nationality Screen
- tapOn: 'No, I do not'

# Relationship status Screen
- tapOn: 'Married'

# Did you change your name after you got married Screen
- tapOn: 'Yes, I did'

# Name changed after marriage Screen
- tapOn:
    id: 'Customer_MaidenName_input'
- inputText: 'Test'
- tapOn: 'Continue'

# Do you have a TIN screen
- tapOn: 'No, I do not'

# Tax liable country Screen
- tapOn: 'Continue'

# Which gender in your password Screen
- tapOn: 'Male'

# Date of birth Screen
- tapOn:
    id: 'Customer_DateOfBirth_input'
- inputText: '12.12.1991'
- tapOn: 'Continue'

# Name and Surname Screen
- tapOn:
    id: 'Customer_FirstName_input'
- inputText: 'John'
- tapOn:
    id: 'Customer_Surname_input'
- inputText: 'Doe'
- tapOn: 'Continue'

# Taxable in the USA screen
- tapOn: 'I confirm that I am not a US tax resident'

# Current Address (google input)
- tapOn:
    id: 'Google-Address_input'
- inputText: 'Test'
- tapOn: .*Wilhelm-.*
- tapOn: 'Continue'

# Confirm Address
- tapOn: 'Continue'

# Agreements Screen
- tapOn:
    id: 'AgreementTermsRevocationBlockedAccount_checkbox'
- tapOn:
    id: 'AgreementBlocking_checkbox'
- tapOn:
    id: 'Agreement_GwG_checkbox'
- tapOn:
    id: 'Agreement_ForeignAuthorities_checkbox'
- tapOn: 'I have read and downloaded all the agreements'

# Open Account screen
- tapOn:
    id: 'Customer_Email_input'
- runScript: generateEmail.js
- inputText: ${output.result}
- tapOn:
    id: 'customerPassword_input'
- inputText: 'AppTest987'
- tapOn: 'Open Account'

# Code Activation Screen
- tapOn:
    id: 'otp0'
- inputText: '9'
- tapOn:
    id: 'otp1'
- inputText: '8'
- tapOn:
    id: 'otp2'
- inputText: '1'
- tapOn:
    id: 'otp3'
- inputText: '2'
- tapOn: 'Verify'

# Welcome to Fintiba Screen
- tapOn: 'Continue'
```

**Additional context**
With maestro test command it works locally.
Structure of the folders:
```
- application
       - maestro
             - generateEmail.js
             - onboarding-process.yaml
 ```
    
Function described above is generateEmail.js:
```
(function generateFormattedString() {
  // Get the current date
  const now = new Date();

  // Format the date as "yyyy-mm-dd"
  const year = now.getFullYear();
  const month = (now.getMonth() + 1).toString().padStart(2, '0'); // Months are zero-indexed
  const day = now.getDate().toString().padStart(2, '0');

  const formattedDate = `${year}-${month}-${day}`;

  // Generate six random digits
  const randomDigits = Math.floor(Math.random() * 1000000)
    .toString()
    .padStart(6, '0');

  // Construct the final string
  output.result = `robot_${formattedDate}_${randomDigits}@test.xyz`;
})();
```
