### ISSUE TITLE
[v.1.36.0] () characters treated as regex even within string

### ISSUE THREAD

**Issue by bullPaul** [mobile-dev-inc/maestro#1763]
**Describe the bug**
Inside `containsDescendants` the text is treated completely like a regular expression despite the string and cannot use parentheses. 

```
- assertVisible:
    id: 'FacilityNameAZ_Contents'
    containsDescendants:
      - text: 'Facility name \(A-Z\)'
      - id: 'Radio'
```

This was mentioned in [Slack](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1717576298244769) as well.

**To Reproduce**

1. Start the simulator
2. Run maestro test ...
3. Test fails on this line just because of the `containsDescendants' text`

**Expected behavior**
Treats the string like a string instead of a regexp or ability to escape those characters as expected like `'Facility name \(A-Z\)'` instead of having to do `Facility name .*`

**Screenshots**
N/A

**Environment information (please complete the following information):**
Maestro version [v.1.36.0]
Platform: [iOS 17.0.0+]
Framework: [React Native with Expo]
Device model and OS version: [iPhone 14+]
Simulator
Host [Mac]

**Workspace (if applicable)**
N/A

**Bugreport output (if applicable)**
N/A

**Additional context**
N/A
