### ISSUE TITLE
[Maestro version, e.g. v1.2.3]

### ISSUE THREAD

**Issue by sasha-yurchenko** [mobile-dev-inc/maestro#1774]
Good afternoon
I can’t get to the required element in a horizontal block.
The first step is to move to this block

```
- scrollUntilVisible:
    centerElement: true
    element:
      id: MagazineHorizontalList
    direction: DOWN
```

Next I try to go to the element in this block

```
- scrollUntilVisible:
  centerElement: true
  direction: right
  element:
    id: MagazineListThirdItem
```

As a result, the scroll does not work.
Construction type is not supported.- scrollUntilVisible:

    direction: right
    container:
      id: "horizontal-list-container"
    element:
      id: "item-5"

How to solve this problem?
