### ISSUE TITLE
[Maestro version, 1.36.0] location permission setting has no effect

### ISSUE THREAD

**Issue by matthiaskmt** [mobile-dev-inc/maestro#1781]
**Describe the bug**
the permission setting in the `launchApp` command doesn't restrict the location permission 

**To Reproduce**
Steps to reproduce the behavior, e.g.:

Launch a test flow with the following start parameters:
```
- launchApp:
    clearState: true
    clearKeychain: true
    permissions:
        all: deny
        location: never
```

**Expected behavior**
All permissions are denied

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-08 at 15 53 35](https://github.com/mobile-dev-inc/maestro/assets/1555742/92fa6ad0-0d76-4450-a92d-233e58b60cb2)

**Environment information (please complete the following information):**

- Maestro version 1.36.0
- Platform: iOS 17.2
- Framework: Native iOS
- Device model and OS version: iPhone 15 Pro Max
- Simulator
- Host Mac M1
