### ISSUE TITLE
Using integer value from JavaScript `outputs` results in a deserialization error

### ISSUE THREAD

**Issue by merveeyenice** [mobile-dev-inc/maestro#1788]
**Describe the bug**
When passing paramaters, outputs are passed as strings so this does not make possible to use speed and timeout values as parametric in scrollUntilVisible command.

**To Reproduce**
I would like to pass speed and timeout value for scrollUntilVisible command from a .js file called "contants.js". 

1. Start the simulator
2. Run `maestro test ...`
3. The Flow fails at parsing file and gives this error:

  ```
  Cannot deserialize value of type int from String "${output.speed.slow_speed}": not a valid int value
  ```

**Expected behavior**

I need to pass `int` values as parameter.

**Workspace (if applicable)**

**.maestro/test.yaml**

```yaml
appId: appId
---
- runScript: constants.js
- launchApp
- scrollUntilVisible:
    element:
      id: ${output.favorites.imageViewVariantPickerArrow}
    direction: DOWN
    speed: ${output.speed.slow_speed}
    timeout: ${output.speed.long_timeout}
```

**.maestro/constants.js**

```js
output.speed = {
  slow_speed: 50,
  default_speed: 70,
  fast_speed: 80,
}
```
