### ISSUE TITLE
Maestro is not able to detect element by `data-testid`

### ISSUE THREAD

**Issue by dgrover-spotnana** [mobile-dev-inc/maestro#1804]
**Describe the bug**
Maestro is not able to detect element by `data-testid` inside `react-native-webview`

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start iOS simulator and open `https://codesandbox.io/s/jovial-kilby-lt778f?file=/src/App.js` inside `react-native-webview` of your react native app
2. Run `maestro studio`
3. In the studio, tap on the element with `data-testid`
4. Maestro won't be able to detect it and would rather give an option to `tapOn` on the `point` or `text`

**Expected behavior**
maestro should be able detect element by `data-testid`

**Screenshots**

https://github.com/user-attachments/assets/8e2e30da-b90d-4e1c-9de9-acf5cdd859ed

**Environment information:**

- Maestro version: 1.36.0
- Platform: iOS Simulator
- Framework: React Native
- Device model and OS version: iPhone 15 Pro - iOS 17.4
- Host: Mac M1

**Additional context**
The issue is **NOT** limited to `react-native-webview` but also occurs in case of a normal browser (chrome/safari etc.)

**Comment by bartekpacia** [comment]
Hey, thanks for the issue and sorry about the problem.

The problem here lies in the React Native app not exposing `data-testid` as "accessibility identifier" (actually it's called `resource-id` on Android and `accessibilityIdentifier` on iOS).

[This SO question is relevant](https://stackoverflow.com/questions/37387640/no-id-for-my-android-ui-testing), [this GH issue](https://github.com/facebook/react-native/issues/7135) as well.

There's not much we can do on Maestro side, since we rely solely on accessibility tree.

**Comment by bartekpacia** [comment]
Yes, this is expected, unfortunately. I assume the browser does not expose `data-testid` as "accessibilityIdentifier".

We can't do anything about it.

**Comment by dgrover-spotnana** [comment]
I can see an experimental support for web flows [here](https://maestro.mobile.dev/advanced/experimental/maestro-webdriver), below is a snippet from your docs for this

```
appId: "https://maestro.mobile.dev"
---
- launchApp
- tapOn:
    id: "Search…"
    index: 1
- inputText: "Tap On View"
- tapOn: "Go to page"
- assertVisible: "Taps on a view on the screen.*"
```

if `browser does not expose data-testid as "accessibilityIdentifier"`, what is the `id` being referred to here ?

**Comment by bartekpacia** [comment]
`id` is literally `id`, from HTML.

You can refer to this example flow (my personal website was the first thing that came to my mind and was easy to reproduce):

```yaml
appId: https://garden.pacia.tech
---
- launchApp
- tapOn:
    id: title-header
- tapOn:
    id: non-existent-id
```

There's HTML element with id `title-header`, so Maestro taps on it.
