### ISSUE TITLE
`tapOn` with `optional: true` parameter doesn't work on iOS

### ISSUE THREAD

**Issue by giangpham96** [mobile-dev-inc/maestro#1807]
**Describe the bug**
It seems like `tapOn` with `optional: true` parameter doesn't work on iOS.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
Having a test like this
```yaml
appId: ${APP_ID}
tags:
  - abc
---
- launchApp:
    permissions: { all: allow } 
- tapOn:
    text: "Dismiss"
    optional: true
...
```

1. Start the simulator
2. Execute the test on an iPhone simulator
3. The Flow fails at ...

```
[Fail]	Tap on (Optional) "Dismiss"
```

**Expected behavior**

It should ignore if it can't find the text with "Dismiss" label

**Environment information (please complete the following information):**

- Maestro version: 1.36.0
- Platform: iOS 17.0
- Framework: Native iOS
- Device model and OS version: iPhone 15 Pro
- Simulator, emulator or physical device: simulator
- Host: Mac M1
