### ISSUE TITLE
Unable to select image from expo-image-picker

### ISSUE THREAD

**Issue by Hosam-hsm** [mobile-dev-inc/maestro#1814]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

I'm using the Expo Image Picker to add images to my app. The Image Picker opens correctly, and I used Maestro Studio to determine the point where the image is located. However, while running the test flow Maestro is unable to select the defined point. 

This issue is happening only on iOS simulator and working fine in android

```
- tapOn:
    id: select-media-btn
- runFlow:
    when:
        platform: iOS
    commands:
        - tapOn: 
            point: "17%,21%"
        - tapOn: Add
```

Using iPhone 15 Pro Max with iOS 17.4

### Actual results

Image is not getting selected while running the flow

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 14 51 18](https://github.com/user-attachments/assets/109e9a0a-2f3c-4c5a-a27a-cd706db91743)

### Expected results

Image should be selected while running the flow

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 15 00 38](https://github.com/user-attachments/assets/682e7ec3-6e1f-4cc2-9bc9-a74aa702ad4b)

### Logs

[hierarchy.txt](https://github.com/user-attachments/files/16310174/hierarchy.txt)

### Maestro version

1.36.0

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)
