### ISSUE TITLE
scrollUntilVisible with optional element does not continue to next line

### ISSUE THREAD

**Issue by vinceramcesoliveros** [mobile-dev-inc/maestro#1907]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

from this documentation: https://maestro.mobile.dev/api-reference/commands/scrolluntilvisible

I added optional value to scrollUntilVisible. But it didn't work as expected. it doesn't skip even if I add optional value.

1. create example flutter project
2. add any yaml file
4. add this example yaml code

anything.yaml
```yaml
appId: com.example.flutter_app
---
- launchApp
- scrollUntilVisible:
    element:
      id: item_list_feature
      optional: true
```

### Actual results

OUTPUT:
❌  Scrolling DOWN until (Optional) id: item_list_feature is visible. 
⬜️ Tap On "Save"

### Expected results

⚪️ Scrolling DOWN until (Optional) id: item_list_feature is visible.
✅ Tap On "Save"

### About app

Framework: Flutter
Version: 3.22.2

### About environment

Java: 18.0.2.1
OS: macOS Sonoma 14.2.1
Architecture: M1

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
❌  Scrolling DOWN until (Optional) id: item_list_feature is visible. 
⬜️ Tap On "Save"
```

</details>

### Maestro version

1.36.0

### How did you install Maestro?

Homebrew
