### ISSUE TITLE
Screenshot is not saved in the same directory as the flow

### ISSUE THREAD

**Issue by bartekpacia** [mobile-dev-inc/maestro#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

```console
mkdir -p .maestro/alpha
```

Then create `.maestro/alpha/flow.yaml` with following contents

```yaml
appId: com.example.example # app doesn't matter
---
- launchApp
- takeScreenshot:
    path: first
- takeScreenshot:
    path: bravo/second
```

### Actual results

2 screenshots are created:
- `.maestro/first.png`
- `.maestro/bravo/first.png`

This doesn't match the behavior described in [`takeScreenshot`](https://maestro.mobile.dev/api-reference/commands/takescreenshot) docs.

### Expected results

I expect 2 screenshots to be created:
- `.maestro/alpha/first.png`
- `.maestro/alpha/bravo/first.png`

### About app

n/a

### About environment

```
$ java -version
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment Homebrew (build 11.0.24+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.24+0, mixed mode)
```

### Logs

n/a

### Maestro version

1.37.7

### How did you install Maestro?

Homebrew
