### ISSUE TITLE
[Feature Request] Test Restart After Failure

### ISSUE THREAD

**Issue by dannmf** [mobile-dev-inc/maestro#1920]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In the testing environment I use, I run a loop performing a specific routine. When a test fails, it does not restart automatically. Is there any way to achieve this, or would it be a feature for the future?

**Comment by bartekpacia** [comment]
Bom dia Daniel, does #1607 sound like what you need? Otherwise, could you draft what would you like us to implement? A new CLI flag e.g.?

**Comment by dannmf** [comment]
From what I understand, in this case, it requires the test to start from another point to test the new implementation.

In my case, it would be more for failures, possibly as a flag in the command like -c. Currently, when the test (using the -c flag) fails, it is necessary to press ENTER to restart it.

Since my test involves a loop and often runs overnight, I need it to store the logs as usual and automatically restart when a failure occurs.

**Comment by bartekpacia** [comment]
Can you clarify what you mean by "I run a loop"? Do you mean:

```console
#!/usr/bin/env sh
command="maestro test ./my_fow"
max_retries=5
retries=0
while true; do
    $command
    
    if [ $? -eq 0 ]; then
        echo "Command succeeded."
        break
    else
        retries=$((retries + 1))
        echo "Command failed. Attempt $retries of $max_retries."
    fi

    if [ $retries -ge $max_retries ]; then
        echo "Command failed after $max_retries attempts."
        exit 1
    fi
done

```

**Comment by dannmf** [comment]
Basically, that's it. In my flow, I use repeat.
```
name: "Realiza rotina com 3000 vendas" 
---
- runFlow: 
    file: ../utils/auth/login_routine.yaml
    label: ' 🔑 Realizando Login'
- runFlow: 
    file: ../utils/access_modules/access_catalog.yaml
    label: '🧪 Acessando Catálogo'
- repeat:
    times: 3000
    commands:
      - runFlow: 
          file: ../catalog/catalog_sale_test.yaml
          label: '🧪 Teste: 1000 Vendas'
```
Would I use this as a command? How would it look?
