### ISSUE TITLE
Android: Swiping not working properly using start and end coordinates in percentages

### ISSUE THREAD

**Issue by smehr123** [mobile-dev-inc/Maestro#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

We are using start and end coordinates in percentages to swipe between different tabs of the app (from left to right , from right to left). The code works fine on iOS but in case of Android it stops swiping LEFT from third tab to fourth tab view id.

I also tried playing with the coordinates but they do not seem to work. Any help would be greatly appreciated!

Following is the code snippet

```
appId: com.example.dev
---
- runFlow:
    file: helpers/signIn.yaml
- swipe:
    from:
      id: ‘first-view-id'
    start: 90%, 50%
    end: 10%, 50%
- swipe:
    from:
      id: ‘second-view-id'
    start: 90%, 50%
    end: 10%, 50%
- swipe:
    from:
      id: ‘third-view-id'
    start: 90%, 50%
    end: 10%, 50%
- runFlow:
    when:
      visible:
        id: ‘fourth-view-id'
    commands:
      - swipe:
          from:
            id: 'fourth-view-id'
          start: 90%, 50%
          end: 10%, 50%
- swipe:
    from:
      id: ‘fifth-view-id'
    start: 10%, 50%
    end: 90%, 50%
- runFlow:
    when:
      visible:
        id: ‘fourth-view-id'
    commands:
      - swipe:
          from:
            id: 'fourth-view-id'
          start: 10%, 50%
          end: 90%, 50%
- swipe:
    from:
      id: ‘third-view-id'
    start: 10%, 50%
    end: 90%, 50%
- swipe:
    from:
      id: ‘second-view-id'
    start: 10%, 50%
    end: 100%, 50%
- assertVisible:
    id: ‘first-view-id'
```

### Actual results

Swiping should happen successfully on Android between the tabs from LEFT to RIGHT and from RIGHT to LEFT as its happening on iOS

### Expected results

It stops swiping LEFT from third tab to fourth tab view id.

### About app

 - Cross platform App
 - React Native App

### About environment

macOS: 14.6.1 (23G93) - Sonoma
Android emulator - Pixel_3a_API_33
Android version: API 33

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.37.9

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by Fishbowler** [comment]
I've checked the docs for swipe: https://docs.maestro.dev/api-reference/commands/swipe

This structure isn't documented:

```
- swipe:
    from:
      id: ‘first-view-id'
    start: 90%, 50%
    end: 10%, 50%
````

I've also checked the [implementation](https://github.com/mobile-dev-inc/Maestro/blob/v1.39.13/maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSwipe.kt) and can't see a variant deserialisation that would include all of these properties. I suspect the bits that are working are working by accident, and should likely be caught by better validation.

What are you expecting here? That it swipes from `90%,50%` of the `first-view-id`?

You've not provided any screenshots, but would this work without the IDs?
