### ISSUE TITLE
Multiple tap on view to access hidden features.

### ISSUE THREAD

**Issue by teresch-a** [mobile-dev-inc/maestro#205]
It would be great if it would be possible to make multiple tap option for a view and key press to access hidden options. For example opening dialog for switching to dev servers on 6 times view click, toggle visibility of debug only options etc. Something like "tapCount" with ability to specify delay between taps.

**Comment by amanjeetsingh150** [comment]
Hey @teresch-a , This can be solved by repeat command we recently added:

Docs: https://maestro.mobile.dev/advanced/loops

```
- repeat:
    times: 6
    commands:
      - tapOn: "button-text"
```

Let me know if this works.
