### ISSUE TITLE
[Question] Is there a way to define the onFlowStart/onFlowComplete hooks in a single flow file and reference it in all other flow files?

### ISSUE THREAD

**Issue by gmkumar08** [mobile-dev-inc/maestro#2063]
I have a setup.yaml file that uses the runScript command to load all the js files (page objects) and I'm loading this setup.yaml file in all my flow files. Instead of using onFlowStart/onFlowComplete hooks in all my flow files, can I just define it within my setup.yaml?

**Comment by Fishbowler** [comment]
Doesn't exist at present. Would be cool to be able to default a bunch of things in the config.yaml. But how could you _unset_ for a run that didn't want it?

**Comment by abedolinger** [comment]
@Fishbowler I don't see that as a blocker to this feature, but it would be great to have global settings at the config.yaml level, and local settings at the file level.

I.e.:

```
# config.yaml
env:
    USERNAME: test@example.com
    PASSWORD: 123
onStart:
   - runFlow: setup.yaml
```

```
# sampleFlow.yaml
env:
    USERNAME: test2@example.com
    PASSWORD: 456
onStart:
  - runFlow: # skip setup.yaml
```

What do you think? I would love to use this so flows can use a common login, for example.
