### ISSUE TITLE
Timeout not working in scrollUntilVisible

### ISSUE THREAD

**Issue by alecalma** [mobile-dev-inc/maestro#2108]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

```
- launchApp:
    clearState: true
- swipe:  
    direction: DOWN
- assertVisible:
    text: "Login"
    enabled: true
- tapOn:
    text: "Login"
- scrollUntilVisible:
    element:
        text: XYZ
    direction: DOWN 
    timeout: 1000
```

### Actual results

As easy as it sounds, the timeout parameter does not work for the method scrollUntilVisible, Maestro keeps scrolling forever.

### Expected results

I expect the test to fail after the timeout duration.

### About app

Native app for android mobile in ReactNative.

### About environment

Pixel 9 Pro API35 from AndroidStudio.

### Maestro version

1.39.0

### How did you install Maestro?

Homebrew
