### ISSUE TITLE
iOS miss `-` Launch Arguments when value type is Bool

### ISSUE THREAD

**Issue by littlema0404** [mobile-dev-inc/maestro#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

```yaml
appId: xxx
- launchApp:
    clearState: true
    permissions:
      userTracking: deny
    arguments:
        argumentA: true
        argumentB: 1
        argumentC: "abc"

```

### Actual results

```swift
CommandLine.arguments // ["argumentA", "true", "-argumentB", "1", "-argumentC", "abc"]
```

### Expected results

```swift
CommandLine.arguments // ["-argumentA", "true", "-argumentB", "true", "-argumentC", "abc"]
```

### About app

Closed source iOS native app

### About environment

Java version
```
openjdk version "17.0.10" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-17.0.10.7.1 (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.10.7.1 (build 17.0.10+7-LTS, mixed mode, sharing)
```

OS and its version
```
macOS 14.6.1（23G93）
```

Processor architecture 
```
M2 arm64
```

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.38.1

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

`-` This is the specification for iOS launch arguments. Currently, only when the YAML value type is Bool, the - sign is not added. However, if the value type is Int or String, the - sign is automatically added.

**Comment by Fishbowler** [comment]
Looks like the intent in #1018 was that you'd access booleans differently?

**Comment by littlema0404** [comment]
Yeh, for here a little bit confused.

like example from #1018 

```swift
 ProcessInfo.processInfo.arguments.contains("isMaestro")
```

The contains method only indicates whether the ‘isMaestro’ launch argument is present, but it doesn’t allow me to retrieve its boolean value.

**Comment by johntmcintosh** [comment]
I ran into this today as was/am confused as well. 

In my case, I was passing one launch argument that was an explicit boolean, and another that was a boolean passed through the yaml environment:

```
appId: ${APP_ID}
---
- launchApp:
    arguments: 
        argA: true
        argB: ${ARG_B_VALUE}
```

and then I'm calling this flow with

```
appId: ${APP_ID}
---
- runFlow: 
    file: common/launch-app.yaml
    env:
      argB: false
```

and with this setup, I'm receiving the raw arguments in my app as:

```
["<path>/MyApp.app/MyApp", "argA", "true", "-argB", "false"]
```

And I have code in my app to extract values directly from `ProcessInfo.processInfo.arguments`, but that code is based on the expectation of arguments being prefixed with `-` or `--` so it's not finding `argA`'s value.
