### ISSUE TITLE
SafariViewService quit unexpectedly.

### ISSUE THREAD

**Issue by LinschotenMelle** [mobile-dev-inc/maestro#2215]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

- maestro test flow.yaml

### Actual results

Right now it seems iOS is very flaky and/or incorrect when it comes to dialogs with Flutter. 
Whenever im running this script on Android is works as expected, but whenever i use iOS emulator im getting the different result every time I run it. In the end of the second run I get the following error: "SafariViewService quit unexpectedly." which i never got until i used this package.

Im using the following yaml code (can also be seen in the video)
```
- tapOn: "Email address"
- assertVisible:
    id: "loginDescription"
- tapOn:
    id: "loginDescription"
- waitForAnimationToEnd
- assertVisible:
    id: "loginDescriptionDialog"
- tapOn:
    point: "50%,25%"
- waitForAnimationToEnd
- assertNotVisible:
    id: "loginDescriptionDialog"
- tapOn:
    id: "loginDescription"
- waitForAnimationToEnd
- tapOn:
    id: "ok"
- waitForAnimationToEnd
- assertNotVisible:
    id: "loginDescriptionDialog"
- hideKeyboard
```

https://github.com/user-attachments/assets/1e72eaeb-d09f-4086-951c-74b210160964

What can be the cause of this?

### Expected results

The same as Android without flaky instances

### About app

The app is a closed source project
- The code can be seen above

### About environment

Iphone 15 plus
iOS 18.0

Maestro 1.39.7
 
MacBook Air 13″
macOS 15.2

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.39.7

### How did you install Maestro?

Homebrew
