### ISSUE TITLE
Workspace Setup/Teardown hooks

### ISSUE THREAD

**Issue by timrijckaert** [mobile-dev-inc/Maestro#2220]
### Use case

We already have the option to hook into the setup and teardown of one test with the use of `onFlowStart` and `onFlowComplete`.  #1206 
However we notice as our code base is growing, we need to perform the same operation with every test.   
For now we have a helper script that performs our setup and teardown and need to copy it in every single YAML file we create.

### Proposal

There is already a more global [configuration object](https://maestro.mobile.dev/api-reference/configuration/workspace-configuration#maestro-configuration). 
I was wondering if something like this would be possible so we have a more global `onFlowStart` / `onFlowComplete`

```yaml
flows:
  - "subFolder/*"
includeTags:
  - tagNameToInclude
excludeTags:
  - tagNameToExclude
onFlowStart:
  - runScript: "setup.js"
onFlowComplete:
  - runScript: "teardown.js"
```
