### ISSUE TITLE
Windows (without WSL) - config.yaml cannot resolve flows

### ISSUE THREAD

**Issue by Vidal-A** [mobile-dev-inc/Maestro#2279]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1. Put the config.yaml in the root directory.
2. Add a flows section to the config.yaml
3. Run "maestro test {root-directory}"

**Config.yaml** 
```
flows:
  - "./scenario/wifi/*"

```

### Actual results

When i use the windows version, from powershell:

**Error message :** 

```
Flow inclusion pattern(s) did not match any Flow files
```

(Works on WSL)

### About environment

WSL Maestro version : 1.39.9
Windows Maestro versions : 1.39.9
Windows 11.
Ubuntu 24.04.1 LTS

### Maestro version

1.39.9

**Comment by Vidal-A** [comment]
Error in my ticket, it doesn't work on either Linux or Windows, the issue is probably with my config.yaml. I consistently get "Flow inclusion pattern(s) did not match any Flow files:"

**Comment by jerone** [comment]
> Error in my ticket, it doesn't work on either Linux or Windows, the issue is probably with my config.yaml. I consistently get "Flow inclusion pattern(s) did not match any Flow files:"

I'm getting the same on Windows. 
@Vidal-A Did you find a solution?

**Comment by Vidal-A** [comment]
> > Error in my ticket, it doesn't work on either Linux or Windows, the issue is probably with my config.yaml. I consistently get "Flow inclusion pattern(s) did not match any Flow files:"
> 
> I'm getting the same on Windows. [@Vidal-A](https://github.com/Vidal-A) Did you find a solution?

Yes, the issue ultimately comes from the Windows version. I necessarily have to go through WLS, which poses a problem for some teams. I shouldn't have closed the ticket ^^"
**It is very important to specify the host on WLS, otherwise no commands will work.**
maestro --host <local_ip> test scenario


Windows KO : 
<img width="430" alt="Image" src="https://github.com/user-attachments/assets/b5c9e8d1-de9e-4711-9373-aed4795d7522" />

Linux OK : 
<img width="740" alt="Image" src="https://github.com/user-attachments/assets/52e114f4-84f5-466b-9cd5-95eb2e053ff5" />


If my config can help, Config.yaml in the scenario folder :

```
flows:
  - "sms_mms/*"
  - "wifi/*"
  - "browsing/*"

executionOrder:
  continueOnFailure: true
  flowsOrder:
    - init_browsing
    - 10.2.4
    - 10.1.2
    - 10.2.1
    - 10.2.2
    - 6.1.2
    - init_sms_mms
    - 5.1.1
    - 5.1.3
    - 5.1.4
    - 5.1.5
    - 5.1.6




```
