### ISSUE TITLE
[Enhancement] Suggestion - Allow a specific comment command to output to the terminal to split up/group steps

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#233]
On some longer flows you end up with a long list of ticks and descriptions for the steps, it would be good to have a way where you could optionally break these up and group certain steps together, e.g.

```
- tapOn:
    id: "nav_home"
### Card Flow
- tapOn:
    id: "nav_card"
```

This would output in the terminal and increase readability/glanceability (could also use a different icon):

```
  ...
  ✅  Tap on id: nav_home
      Card Flow
  ✅  Tap on id: nav_card  
  ...
```
