### ISSUE TITLE
onFlowFailure hook when a step failed

### ISSUE THREAD

**Issue by Revono** [mobile-dev-inc/Maestro#2345]
### Use case

Hi all!

I absolutely love this framework! 

The only thing I’m missing is a simple onFailure parameter that allows executing a .js (runScript) script when something inside my Flow fails. I went through the entire documentation, but I couldn’t find anything like this.

Would implementing this be a big task? 

### Proposal

Something like this would be sooooo big:

```
---
appId: com.sample.app
---
- try:
    - assertVisible: "Living Room"

- runScript:
    file: update_notion_passed.js
    env:
      pageId: "xyz" 

- onFailure:
    - runScript:
        file: update_notion_failed.js
        env:
          pageId: "xyz" 
```

**Comment by Fishbowler** [comment]
If you want to capture failure actions inside your test rather than as part of CI or similar, you can use the hooks.

I don't think the Maestro team would want to introduce additional try/catch logic - the more logic you add to tests, the more you want tests for your tests.

Here's an example of how you can achieve what you want using the existing tooling.

```
appId: com.sample.app
onFlowStart:
  - evalScript: ${output.flowSuccess = "0"}
onFlowComplete:
  - runScript:
      when:
        true: ${output.flowSuccess == "0"}
      file: update_notion_passed.js
        env:
          pageId: "xyz" 
---
- assertVisible: "Living Room"
- evalScript: ${output.flowSuccess = "1"}
```

**Comment by Revono** [comment]
> If you want to capture failure actions inside your test rather than as part of CI or similar, you can use the hooks.
> 
> I don't think the Maestro team would want to introduce additional try/catch logic - the more logic you add to tests, the more you want tests for your tests.
> 
> Here's an example of how you can achieve what you want using the existing tooling.
> 
> ```
> appId: com.sample.app
> onFlowStart:
>   - evalScript: ${output.flowSuccess = "0"}
> onFlowComplete:
>   - runScript:
>       when:
>         true: ${output.flowSuccess == "0"}
>       file: update_notion_passed.js
>         env:
>           pageId: "xyz" 
> ---
> - assertVisible: "Living Room"
> - evalScript: ${output.flowSuccess = "1"}
> ```
> 
> (I'm sure there's a ticket in here somewhere about exposing success/error state on the `maestro` object in JS)

hi thanks for the fast response :)

i tried to find „ exposing success/error state to js“ but i had no success to find it. do you know how?

**Comment by Fishbowler** [comment]
Feel free to create one, and I'll merge em if I find it.

**Comment by Revono** [comment]
@Fishbowler To be honest, I’m not sure how you mean to create one. If I knew, I’d already have done it.

**Comment by Fishbowler** [comment]
> (I'm sure there's a ticket in here somewhere about exposing success/error state on the maestro object in JS)

I meant a ticket on the issue tracker.

I don't believe that the functionality exists right now to automatically know at that hook whether success or failure has occurred. I've done a little experimentation locally, and can't find anything better than the pattern I've suggested above. Adding something like `${maestro.flowResult}` would remove some of that boilerplate.

I considered whether something like an `onFlowFailed` hook, but you get into complications. Would an `onFlowComplete` hook also run? Do you also need `onFlowSuccess`? In what order should they run? Giving one flow with status gives control to the developer.

**Comment by Revono** [comment]
@Fishbowler
I think the already existing onFlowComplete is enough, but enhanced with your idea {maestro.flowResult}—that way, it becomes dynamic since onFlowComplete always executes, whether the flow succeeds or fails.

Your idea is really good!

**Comment by Revono** [comment]
@Fishbowler Should I create a new issue, or what do you think is the best approach? I feel like you have a better understanding of how this should be implemented.

**Comment by Fishbowler** [comment]
My feeling is that this hook would be useful, but...

In the situation where you've got multiple teardown steps, you might also need the flow result, because of specific ordering of stuff.


```
appId: com.example
onFlowComplete:
  - runScript: a-thing-we-always-do-1.js
  - runScript:
      when:
        true: ${output.flowSucceeded == false}
      file: when-things-fail.js
  - runScript: a-thing-we-always-do-2.js
```

I'm imagining there's API calls or something in each of those that has to happen in a particular sequence, like cleaning up data and reporting.

If we just use hooks, there's going to be an execution order (either onFlowComplete then onFlowFailure, or the other way around).

I think this is all another ticket that needs making though.
