### ISSUE TITLE
inputText flakily skips numbers in number strings on iOS

### ISSUE THREAD

**Issue by meatnordrink** [mobile-dev-inc/Maestro#2382]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1. `inputText: '4049389283'`

However, it's flakey. But it's happening pretty consistently with number strings for us. (Since we've switched to Expo, which might suggest that either the problem is related to Expo, or to something which changed with Maestro/XCode/MacOS in the past couple months, since we haven't been running these same tests against our bare React Native app during the time we've been transitioning to Expo, and we weren't seeing this problem a few months ago in an identical test against a functionally identical app.)

### Actual results

`inputText: '4049876574'`

Result is sometimes 409876574.

* I have tried passing numbers or number strings (numbers with quotes around them) with the same results.
* Breaking the string up into two parts sometimes addresses the issue, but usually simply results in a different number being dropped. 
* Breaking it up into no more than two numbers per `inputText` works. 

### Expected results

The number string passed to `inputText` is entered in the given field. 

### About app

React Native Expo app. Expo version 0.22.0. 

### About environment

M1 Macbook Pro, Sequoia 15.3.2. XCode 16.2. 

Running on iPhone 11 emulator, iOS 17.2. 

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.39.13

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

Reported in the Slack by at least one other user - https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1742234249567009

**Comment by tafty** [comment]
To mitigate this issue I've implemented a utility flow, `input-text.yaml` to enter text:

```
# Required env:
#   INPUT_TEXT
appId: ${APP_ID}
---

- evalScript: ${output.counter = 0}
- repeat:
    optional: true
    while:
      true: ${output.counter < INPUT_TEXT.length}
    commands:
      - inputText: ${INPUT_TEXT.charAt(output.counter)}
      - evalScript: ${output.counter = output.counter + 1}
```

Which is called like this:

```
- runFlow:
    file: "input-text.yaml"
    env: 
      INPUT_TEXT: "some text"
```

**Comment by abbbe** [comment]
Never had issues with normal TextInput fields, but it affects OTP entry screen which has a bunch of TextInput (one per OTP digit) and custom handler moving focus to between them. @tafty's solution works well for me, but it would be nice to have a parameter for typing rate.

**Comment by timostroehlein** [comment]
I'm also experiencing this issue within GitHub Actions, locally everything works fine. It seems like it could be due to limited resources compared to running the flows locally. The workaround of @tafty resolved this issue for now, thanks!

**Comment by alexandrubalanean** [comment]
Another workaround is to retry input until the expected value is visible

```yaml
- repeat:
    while:
      notVisible: ${username}
    commands:
      - tapOn: ${usernameField}
      - eraseText
      - inputText: ${username}
```
