### ISSUE TITLE
Maestro Web not detected when appId is environment variable

### ISSUE THREAD

**Issue by pandeiro** [mobile-dev-inc/Maestro#2383]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Maestro appears to use the presence of (http|s) in the `appId`/`url` field to resolve whether flows are browser or native-targeted.

When a flow uses an environment variable for this value (eg `maestro test -e APP_ID="http://localhost:3000" flow.yaml`), the current Maestro version fails to resolve and run tests in the browser.

### Actual results

Maestro will report insufficient shards, as if it expects mobile simulators/emulators to run, despite the flows targeting an 'http*' appId.

### Expected results

Maestro should wait to resolve environment variables before any resolution/dispatch logic depending on the value of appId.

### About app

Using an environment variable for `appId` is a common pattern especially for testing universal apps.

### About environment

macOS Sonoma 14.5 (23F79)
openjdk version "23" 2024-09-17

### Logs

<details>
<summary>Logs</summary>

```
$ maestro test -e APP_ID='http://localhost:3000' flow.yaml

Want to use 0 devices, which is not enough to run 1 shards. Missing 1 device(s).
Not enough devices connected (1) to run the requested number of shards (1).
```

</details>

### Maestro version

1.39.13

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by CodingItWrong** [comment]
I'm seeing the same problem. It looks like a workaround that will work is installing a simulator/emulator on the CI machine, even though it's not actually necessary for the test. For example, adding this step on a macOS runner fixed it for me:

```
      - name: 🏗 Set up simulator to work around https://github.com/mobile-dev-inc/Maestro/issues/2383
        uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 16 Pro Max
```

**Comment by CodingItWrong** [comment]
@Angelk90 that error message isn't the "insufficient shards" error that this bug relates to; it seems to be a different issue than this one. So I doubt my full workflow will help with that. But here is my workflow if it helps anyone:

```yaml
name: "Build Web"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maestro-web:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Project
        uses: ./.github/actions/setup-node-project # just installs pnpm, node, and and dependencies

      - name: 🏗 Configure Maestro
        uses: dniHze/maestro-test-action@v1

      - name: 🏗 Set up simulator to work around https://github.com/mobile-dev-inc/Maestro/issues/2383
        uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 16 Pro Max

      - name: Build React Native Web 📦
        run: pnpm run build:web

      - name: Run
        run: npx serve -p 8081 dist &

      - name: 🧪 Run Maestro tests
        run: pnpm maestro:web .maestro/LaunchTest.yaml

```

**Comment by mikehuebner** [comment]
Seeing the same issue just running a simple test locally.

```
Unable to launch app http://localhost:4000: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch http://localhost:4000.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "http://localhost:4000" failed.
```

If I do `appId: http://localhost:4000` it works fine. It doesn't effect any child flows I have under `runFlow when platform: web` either. So as long as the root file has this, then its good.

**Comment by mikehuebner** [comment]
Well, this feels silly but it works.

```yml
# Temporary until this bug is fixed:
# https://github.com/mobile-dev-inc/Maestro/issues/2383
appId: http://localhost:4000
---
- launchApp: ${APP_ID} # This works around the above issue, couldn't tell you why
```

**Comment by mikehuebner** [comment]
New issue, if I'm using a config file and then doing something like `maestro test flows/*` to kick things off, this work around doesn't work anymore. It still complains. Going to try a few things to figure this out.

**Comment by mikehuebner** [comment]
I guess a way to work around this would be to just have an entry file like `web.yml` that will only run for web related actions and then do a sequential run through of things.

**Comment by mikehuebner** [comment]
Just an update, this has been how I'm doing web flows vs native.

Web:
```yml
# Temporary until this bug is fixed:
# https://github.com/mobile-dev-inc/Maestro/issues/2383
appId: http://localhost:4000
jsEngine: graaljs
---
- launchApp: ${APP_ID} # This works around the above issue, couldn't tell you why

- runFlow:
    label: Run all flows for the web path only
    when:
      platform: Web
    commands:
      # Mimic the `config.yml` until the above Github Issue is resolved, but it doesn't support
      # recursive so we have to be very manual
      - runFlow: flows/flow-1.yml
      - runFlow: flows/auth-flow.yml
      - runFlow: flows/checkout-flow.yml
      - runFlow: flows/logout.yml
```

Native uses a config file with a similar path
```yml
# config.yml
# For web, this is ignored, and we need to be specific about our flows in the `web.yml` file
# until this bug is resolved: https://github.com/mobile-dev-inc/Maestro/issues/2383

flows:
  - flows/**

executionOrder:
  flowsOrder:
    - landing
    - login
    - checkout
    - logout
```
