### ISSUE TITLE
Allow to set permission valie via paramaters

### ISSUE THREAD

**Issue by dwightdhooge** [mobile-dev-inc/Maestro#2416]
### Use case

The launchapp command is specified in a subflow that is used by several tests. Based on the test case we want to set the value of some permissions on allow, deny, unset ... 

```
- launchApp:
    clearState: true
    permissions:
      location: ${PERMISSION_LOCATION}
```

Currently it seems not to be possible to do that, it does not pick up the parameter value. 

### Proposal

Allow expression when defining permission values.
