### ISSUE TITLE
continueOnFailure not respected when flows in a subdirectory

### ISSUE THREAD

**Issue by ben-pomelo** [mobile-dev-inc/Maestro#2469]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Create maestro/config.yaml like so:
```
flows:
  - "**"
executionOrder:
  continueOnFailure: false
  flowsOrder:
    - firstFlow
    - subdir/*
    - lastFlow
```

Make sure there are tests inside subdir.

Introduce a bug that causes `firstFlow` to fail, and then run the entire directory with

```
maestro test maestro
```

### Actual results

All the tests inside `subdir` run after firstFlow fails. 

### Expected results

It should return immediately instead and NOT run all the tests inside `subdir`. This issue seems to be specifically with subdirectories.

### About app

This issue happens in both iOS and Android.

### About environment

This issue happens both locally (2021 M1 Macbook Pro) and in Expo EAS Workflow `maestro` jobs.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.40.1

### How did you install Maestro?

Homebrew
