### ISSUE TITLE
Allow filtering of tags using AND rather than OR

### ISSUE THREAD

**Issue by prolificcoder** [mobile-dev-inc/maestro#2494]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Based on the docs https://docs.maestro.dev/cli/tags multiple matching should act as AND

Have four flow files...

```
        appId: com.example.app
        tags:
          - regression
          - smoke
        ---
        - launchApp
        - tapOn: "text:SomeElementOnScreenA"
```

```
        appId: com.example.app
        tags:
          - regression
          - experience
        ---
        - launchApp
        - tapOn: "text:SomeElementOnScreenB"
```

```
    appId: com.example.app
        tags:
          - experience
          - smoke
        ---
        - launchApp
        - tapOn: "text:SomeElementOnScreenC"
```

```
        appId: com.example.app
        tags:
          - regression
        ---
        - launchApp
        - tapOn: "text:SomeElementOnScreenD"
```
Run maestro with 
 maestro test --include-tags="regression,experience" .

### Actual results

All 4 are executed. 

### Expected results

Only flow_B.yaml should be executed, as it is the only flow containing both the regression and experience tags.

### About app

Nothing specific about this app

### About environment

![Image](https://github.com/user-attachments/assets/feb6d6de-0c86-4319-9aff-15282f5c6422)

nothing specific 

### Logs

<details>
<summary>Logs</summary>

```
[Failed] flow_A (1s) (Unable to launch app com.example.app: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch com.example.app.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "com.example.app" failed.
)
[Failed] flow_D (1s) (Unable to launch app com.example.app: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch com.example.app.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "com.example.app" failed.
)
[Failed] flow_C (1s) (Unable to launch app com.example.app: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch com.example.app.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "com.example.app" failed.
)
[Failed] flow_B (1s) (Unable to launch app com.example.app: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch com.example.app.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "com.example.app" failed.
)

4/4 Flows Failed
```

</details>

### Maestro version

1.40.2

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

This is bug with test filtering not with running tests.
