### ISSUE TITLE
Support Multi-Device Workflows

### ISSUE THREAD

**Issue by jasperaelvoet** [mobile-dev-inc/Maestro#2563]
### Use case

Maestro does not seem to be supporting running a flow that involves multiple devices. In cases for a social media app, or multiplayer game, there is no possibility to test multi device interactions.

### Proposal

I've put together an example YAML file that is easy to use, which allows for running specific commands on specific devices. Here it sends a message from one device to the other, and the other device checks if the message is successfully received.

```YAML
appId: com.jasperaelvoet.HuntingGame
name: message test
description: |
  Example workflow on how a multi device flow could work.


# Specify the number of devices to run the test on, or a list of device names, or device ids.
devices: 2 
devices:
  - iPhone 15
  - iPhone 15 Pro

---
- launchApp # Run on all devices by default
- selectDevice:
    device: 0 # Allow selection on a device by index
    commands:
      - inputText: "This is a message send from device 0!"
      - tapOn: "Send Message"
- selectDevice:
    device: "iPhone 15 Pro" # Also allow selection on a device by name
    commands:
      - assertVisible: "This is a message send from device 0!"
      - inputText: "Received a message from device 0, this is a message by device 1!"
      - tapOn: "Send Message"
```

### Anything else?

Let me know how likely it is this gets implemented, thanks!
