### ISSUE TITLE
[Android] Vertical scroll not working inside a webview rendered inside the activity

### ISSUE THREAD

**Issue by aakash1313** [mobile-dev-inc/maestro#277]
We have a use case where we have to launch google custom tabs and perform a vertical scroll inside that , but it seems that is not scroll on it. 

Here's a screen record with a snippet of the script : 

```
- tapOn:
    text: "Sign in"
    optional: true    
- tapOn:
    text: "olmuitesting2@gmail.com"
    optional: true
- tapOn:
    text: .*Microsoft*.
    optional: true    
- scroll      
- tapOn:
    text: "Allow"
    rightOf: "Cancel"

```

![screenshot-1665678160818](https://user-images.githubusercontent.com/3194646/195653479-24fa68a7-25ef-40e9-93f1-279d9018a05e.png)
