### ISSUE TITLE
Allow platform specific identifiers for tapOn and assertions

### ISSUE THREAD

**Issue by tajchert** [mobile-dev-inc/maestro#310]
As most apps have very similar UX flows on both platforms, however in most cases developers do not use same id's for views on both platforms - it would be great to have the support of platform-specific id's. One that would use different for Android and iOS depending on which platform tests are running at.

Proposition:

```
- assertVisible:
    id: productName
- assertVisible:
    id:
      ios: productDescription
      android: product_desc
```
So on both platform we have a common id of `productName` but we have different id for product description so iOS will use `productDescription` and android would use `product_desc`.  Assertion is just an example as this feature should be connected to id's in other usages as well (ex. `tapOn` as well).

This would allow to share across platforms most of the test in many apps (in my case it would probably allow to have 95% of same tests).
