### ISSUE TITLE
Expand conditional runFlow based on the variable passed in to the test

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#315]
Use case:
I have a test that can go down three paths, but I know beforehand which path it will go down based on the variables I am passing in. It would be nice to be able to choose which subFlow to run based upon that, rather than having to take test time up checking if elements are visible x3 before going down that route.

Potentially something like:

```
...
- runFlow:
    when:
      variable: ${var1}
    file: outcome1.yaml
 - runFlow:
    when:
      variable: ${var2}
    file: outcome2.yaml
- runFlow:
    when:
      variable: ${var3}
    file: outcome3.yaml
...
```
