### ISSUE TITLE
Allow inline parameters to accept parameters.

### ISSUE THREAD

**Issue by colbyharrison** [mobile-dev-inc/maestro#351]
Passing parameters into an inline parameter throws an error

```
java.lang.IllegalArgumentException: No group with name {ANSWER}
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1060)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182)
        at kotlin.text.Regex.replace(Regex.kt:179)...
```

Example usage:
```
appId: some.app.id
---
- runFlow:
    when:
      visible:
        text: ${ANSWER}
    file: click_answer.yaml
    env:
      INPUT: ${ANSWER}
- runFlow:
    when:
      notVisible:
        text: ${ANSWER}
      visible:
        text: "None of the above"
    file: click_answer.yaml
    env:
      INPUT: "None of the above"
```
