### ISSUE TITLE
[FeatureRequest] Point format

### ISSUE THREAD

**Issue by StanKocken** [mobile-dev-inc/maestro#363]
Today:

```
- tapOn:
    point: 100,200    # This command will tap on point x:100 y:200 on the screen (in pixels)
```

We can only type in pixels, which is very device dependent. How can we make this device-independent?

Proposal:

```
- tapOn:
    point: 100,200    # This command will tap on point x:100 y:200 on the screen (in pixels)
- tapOn:
    point: -100,200    # This command will tap on point x:(screen width - 100) y:200 on the screen (in pixels), allowing to target elements on the right or bottom without knowing the screen size
- tapOn:
    point: "80%,20%"    # This command will tap on point x:80% of screen width (so 960 pixel is screen is 1200px) y:20% on the screen height (so 720 pixel is height is 3600 px)
```
