### ISSUE TITLE
Use screen size to determine start/end points

### ISSUE THREAD

**Issue by jrexd** [mobile-dev-inc/maestro#376]
With devices varying in size, it would be super convenient to specify a start and end point for tapping, swiping etc. based off of the screen size width * percentage and screen size height * percentage. Something like:

```
swipe:
  direction: UP
  start:
    xPercent: 50
    yPercent: 75
  end:
    xPercent: 50
    yPercent: 25
```
