### ISSUE TITLE
Launch the app with a specific locale

### ISSUE THREAD

**Issue by mganchas** [mobile-dev-inc/maestro#393]
Hey there!

I need to run tests against our apps in English, German, etc, to assert behavior is correct in different languages (sometimes we show/hide features depending on locale).

Would be really nice to have that as an optional parameter on the `launchApp` command:

```
- launchApp:
    appId: "com.example.app"
    clearState: true
    clearKeychain: true   # optional: clear *entire* iOS keychain
    locale: 'pt' # optional
```
