### ISSUE TITLE
Global variables file

### ISSUE THREAD

**Issue by jrexd** [mobile-dev-inc/maestro#409]
It would be awesome to have a `variables.yaml` file that could be used for each test. If the test has `env` variables listed at the top, it overrides the value in `variables.yaml`.

Ex:

`variables.yaml`

```
appId: com.example
---
- variables:
    x: Hello
    y: World!
```

`test.yaml`

```
appId: com.example
env:
  y: Test World!
---
- launchApp
- tapOn: ${x}    # Taps on "Hello"
- tapOn: ${y}    # Taps on "Test World!"
```
