### ISSUE TITLE
Allow tapOn a view and hold it during some time

### ISSUE THREAD

**Issue by cenci7** [mobile-dev-inc/maestro#420]
It would be great to have some way to press a view and hold it during some seconds.

I didn't find anything in the docs related with this, the `repeat` doesn't work in that way, and the `longPressOn` doesn't last as much as I wanted.

```
# flow.yaml

appId: "com.example.myfirstapp"
---
- launchApp
- assertVisible: "hello"

- tapOn: "hello"
    - time: 10000
    
- longPressOn: "hello"
    - time: 10000
```

**Comment by cenci7** [comment]
I close the issue because with the last update I can do the same as before without coordinates 🏆 

```
- swipe:
      from: "blabla"
      direction: RIGHT
      duration: 12000
```
