### ISSUE TITLE
Fail to run on AWS Device Farm for Android >= 10

### ISSUE THREAD

**Issue by Almouro** [mobile-dev-inc/maestro#425]
Hi! Thanks for providing Maestro to the community! ❤️

Trying to run Maestro in AWS Device Farm, I've noticed Android devices with version 10 and above will fail to run Maestro (basically devices supporting `abb_exe`)

It fails here: https://github.com/mobile-dev-inc/dadb/blob/master/dadb/src/main/kotlin/dadb/Dadb.kt#L85 seemingly printing out the output of running `adb shell cmd package` as if everything after `package` was ignored:

```
java.io.IOException: Failed to install apk /tmp/maestro-app8381517088354451654.apk: Install failed: Package manager (package) commands:
  help
    Print this help text.

  path [--user USER_ID] PACKAGE

...

	at dadb.Dadb$DefaultImpls.install(Dadb.kt:85)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:424)
	... 15 more
```

If I run Dadb from source on AWS, I'm running into the same issue. 
I can log the commands sent via abb:

For instance, with:
```kt
val dadb = Dadb.discover()
val workingDir = System.getProperty("user.dir")
dadb?.install(File(workingDir + File.separator + "blank.apk"))
```
I see:
```
host:devices
host:transport:R9AR207LM2J
host:features
host:transport:R9AR207LM2J
abb_exec:packageinstall-S1656660
```

If I force dadb to use the second version to install an APK (without abb), it works succesfully.

Kinda wondering if there is an issue with the null symbol \u0000 not being recognized somehow on AWS machines. 
AWS Device Farm runs with Ubuntu 14 LTS / Java 8 / adb 1.0.39. 
I've upgraded both `java` and `adb` and I'm still running in the same issue though

Any ideas what could be going on, what to try out next?

**Comment by vibin** [comment]
Hi @Almouro - are you using Custom test environments in AWS device farm?
If yes, can you share the `install` and `pre_test` phases of your AWS device farm script?

**Comment by Almouro** [comment]
Hi @vibin, sure here's a simple example to reproduce:

```yml
version: 0.1

phases:
  install:
    commands:
      - curl -Ls "https://get.maestro.mobile.dev" | bash
      - export PATH="$PATH":"$HOME/.maestro/bin"
      - echo YXBwSWQ6IGNvbS5leGFtcGxlCi0tLQotIGxhdW5jaEFwcAotIGFzc2VydFZpc2libGU6IC4qLioK | base64 -d > test.yaml
  test:
    commands:
      - maestro test test.yaml
```

**Comment by vibin** [comment]
> Hi @vibin, sure here's a simple example to reproduce:
> 
> ```yml
> version: 0.1
> 
> phases:
>   install:
>     commands:
>       - curl -Ls "https://get.maestro.mobile.dev" | bash
>       - export PATH="$PATH":"$HOME/.maestro/bin"
>       - echo YXBwSWQ6IGNvbS5leGFtcGxlCi0tLQotIGxhdW5jaEFwcAotIGFzc2VydFZpc2libGU6IC4qLioK | base64 -d > test.yaml
>   test:
>     commands:
>       - maestro test test.yaml
> ```

Hi @Almouro, you mentioned you tried upgrading ADB. Is that done as part of the install phase? Can you share the snippet for that?

**Comment by Almouro** [comment]
Indeed, here goes:

```yaml
version: 0.1

phases:
  install:
    commands:
      # Upgrade java
      - java -version
      - curl -s "https://get.sdkman.io" | bash
      - source "$HOME/.sdkman/bin/sdkman-init.sh"
      - sdk install java
      - echo "Java upgraded"
      - java -version
      # Upgrade adb
      - adb version
      - wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
      - unzip platform-tools-latest-linux.zip
      - export PATH=$(pwd)/platform-tools:$PATH
      - echo "ADB upgraded"
      - adb version
      # Install Maestro
      - curl -Ls "https://get.maestro.mobile.dev" | bash
      - export PATH="$PATH":"$HOME/.maestro/bin"
      - echo YXBwSWQ6IGNvbS5leGFtcGxlCi0tLQotIGxhdW5jaEFwcAotIGFzc2VydFZpc2libGU6IC4qLioK | base64 -d > test.yaml
  test:
    commands:
      - maestro test test.yaml
```
