### ISSUE TITLE
Maestro intermittently fails to execute steps in a flow

### ISSUE THREAD

**Issue by imGurpreetSK** [mobile-dev-inc/maestro#444]
Preface: This has happened intermittently to me 3 times out of 11 runs.

Context: Certain steps are missed while executing a flow. For the flow attached alongwith, maestro failed to execute `tapOn: "Login"` command all 3 times.

Flow:
``` 
# Basic login flow

appId: com.jobget
---
  - launchApp
  - tapOn: "Login"
  - tapOn:
      text: "While using the app"
      optional: true
  - tapOn: "Continue as a job seeker"
  - tapOn: "Email address"
  - inputText: "gurpreetjs50@yopmail.com"
  - tapOn: "Password"
  - inputText: "Gurpreet@123#"
  - tapOn: "Login"
```

Attachment:

https://user-images.githubusercontent.com/11317262/204097807-3e6eb861-9f58-4ac3-b07a-9b12b7feb331.mov
