### ISSUE TITLE
Bug in setting javascript output as an env var value

### ISSUE THREAD

**Issue by Leland-Takamine** [mobile-dev-inc/maestro#460]
Given these files:

```
# test.yaml
appId: com.example
---
- runScript:
    file: "test.js"
    env:
        GROUP_NAME: ${1}
```
```
// test.js
throw new Error(GROUP_NAME)
```

When you run `maestro test test.yaml`, it produces the following error:

```
org.mozilla.javascript.JavaScriptException: Error: ${1} (test.js#1)
```

The error prints out the string `${1}` which means that the brackets were not properly evaluated in the test.yaml file.

Reported by @maraujop
