### ISSUE TITLE
tapOn taps on the view twice

### ISSUE THREAD

**Issue by sregg** [mobile-dev-inc/maestro#469]
We have a tag component that you can toggle on and off.
when using `tapOn`, maestro seems to tapping on that view twice, one selecting the tag and again unselecting it.
Is there a way to fix that?

Here's the screen record video: https://photos.app.goo.gl/R9JEjvDMnt3fFFpa9

**Comment by Leland-Takamine** [comment]
Yes you can disable this behavior using `retryTapIfNoChange: false`:

```yaml
- tapOn:
    text: your-text
    retryTapIfNoChange: false
```
