### ISSUE TITLE
tapOn doesn't work sometimes 

### ISSUE THREAD

**Issue by Abhisha1** [mobile-dev-inc/maestro#501]
**Maestro version**: 1.17.2
**Simulator**: iPhone 14 Pro, iPhone 13 Pro (iOS version 16.1)

## Description
Hi there, I recently tried to use Maestro for e2e testing in our iOS app. The problem I am seeing is that on a certain screen, Maestro considers the tapOn step to be complete but the button has not actually been tapped. I can resolve this by repeating the clicking step twice but was hoping I someone could some assistance as to why this is happening and provide a fix 😄 

## Reproducing the issue
Test file
```
appId: APPID
---
- launchApp:
    appId: "APPID"
    clearState: true
    clearKeychain: true
...

- tapOn: "Security Code, Use a 4-digit security code"

```
The command to tap on the button is based on what was returned from the maestro studio.

When the test runs, Maestro considers the tap to be successful however the app screen shows that the "Security code, Use a 4-digit security code" button has not been tapped as the screen has not changed.

You can see this in the video below 
![maestrobug](https://user-images.githubusercontent.com/35671786/207505070-b006beed-e8a9-46e5-9406-beccf5e6ef18.gif)

This seems to be similar to the issue reported here: https://github.com/mobile-dev-inc/maestro/issues/495

cc: @h-zuo
