### ISSUE TITLE
Use Index of Repeat Loop for selecting elements

### ISSUE THREAD

**Issue by spoeck** [mobile-dev-inc/maestro#516]
I have a list with n TextFields. Every TextField has the same label. My goal is to go through each field and enter a value. For this reason I would like to use the index of the current run as the index for the tapOn execution.

My idea is something like following:
```yaml
- repeat:
    times: 3
    commands:
      - tapOn: 
          text: "InputFieldLabel"
          index: ${indexOfRepeat}
      - inputText: "value"
```

Or is there any solution which I have missed to read in the docs?
