### ISSUE TITLE
[Feature Request]: Structuring flow output with "echo"

### ISSUE THREAD

**Issue by spoeck** [mobile-dev-inc/maestro#517]
For debugging or a better structure of the flow output, I have one suggestion to make an operator like "echo" or "log":

```yaml

# someFlow.yaml
- runScript: scripts/global_dev.js

- echo: "---"

- echo: "Login user with admin-role: ${output.email}"
- tapOn: "Email*"
- inputText: ${output.email}

- echo: "---"

- echo: "Test menu on Homescreen"
- tapOn: "menu"
- tapOn: "option1"
```

Terminal output:
Running on iPhone 14 Pro Max - iOS 16.1 - D3603182-1616-4787-AA8C-750EDEAE1A63      
                                                                                    
 ║                                                                                  
 ║  > Flow                                                                          
 ║                                                                                  
 ║    ✅  Run scripts/global_dev.js
 ║    ✅  ---      
 ║    ✅  Login user with admin-role: test@example.com
 ║    ✅  Tap on "Email"                                                         
 ║    ✅  Input text test@example.com
 ║    ✅  ---                                        
 ║    ✅  Test menu on Homescreen
 ║    ✅  Tap on "menu"   
 ║    ✅  Tap on "option1"
