### ISSUE TITLE
Serializing error when running flows with environment variables of type long

### ISSUE THREAD

**Issue by edgarfroes** [mobile-dev-inc/maestro#520]
I get an error when trying to run the following flow:

File `error.yaml`:
```yaml
appId: com.foo.xoo
---
- extendedWaitUntil:
    visible: ${GENERIC_TEXT}
    timeout: ${TIMEOUT_IN_MS}
```
Command:
``` bash
maestro test -e GENERIC_TEXT="Foo Xoo Bar" -e TIMEOUT_IN_MS=360000 error.yaml
```
Error:
```
Could not parse Flow file:

Cannot deserialize value of type `java.lang.Long` from String "${TIMEOUT_IN_MS}": not a valid `java.lang.Long` value
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[0]->maestro.orchestra.yaml.YamlFluentCommand["extendedWaitUntil"]->maestro.orchestra.yaml.YamlExtendedWaitUntil["timeout"])
```

It's basically not letting me add any variables of type `long`. If I replace `${TIMEOUT_IN_MS}` with `360000`, it'll work just fine.

**Edit:** Running Maestro 1.17.4 on MacOS Ventura 13.1, MacBook M1 Max 16". Maestro was installed with homebrew.
