### ISSUE TITLE
UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by diegolmello** [mobile-dev-inc/maestro#522]
```yaml
appId: com.apple.Preferences
---
- launchApp
- tapOn: 'General'

```

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1671214617809709

[2022-12-19_130133.zip](https://github.com/mobile-dev-inc/maestro/files/10260782/2022-12-19_130133.zip)
