### ISSUE TITLE
Docs - typo in App Lifecycle example

### ISSUE THREAD

**Issue by b099l3** [mobile-dev-inc/maestro#567]
On the [App Lifecycle page](https://maestro.mobile.dev/reference/app-lifecycle), the example for clearing the app state before launching is missing a `-` at the start:

```
launchApp:
    appId: "com.example.app"
    clearState: true
    clearKeychain: true   # optional: clear *entire* iOS keychain
    stopApp: false # optional (true by default): stop the app before launching it
```

should be:

```
- launchApp:
    appId: "com.example.app"
    clearState: true
    clearKeychain: true   # optional: clear *entire* iOS keychain
    stopApp: false # optional (true by default): stop the app before launching it
```
