### ISSUE TITLE
Flow file is invalid

### ISSUE THREAD

**Issue by stevenosse** [mobile-dev-inc/maestro#582]
Hello

I'm trying to create a common sub flow to fill a form involved in multiple flows, but i'm getting an error i'm not able to understand, since i don't have much details.

The full error is :
`Flow file is invalid: path_to_path/create_customer.yaml`

The `create_customer.yaml` flow file content:

```yaml
appId: APP_ID
---
- tapOn: New
- tapOn: "M"
- tapOn: "*Name"
- inputText: John
- tapOn: "Create
```

> This is a sub flow and it's never executed alone

Is it possible to have a more explanative error ? A verbose flag that could enable the display of what happens behind.

ENV: 
macOS Monterey 12.5.1
maestro version 1.18.5
