### ISSUE TITLE
[Bug] JavaScript dates support

### ISSUE THREAD

**Issue by stevenosse** [mobile-dev-inc/maestro#590]
Hello

I'm not able to execute some javascript dates methods, necessary for my tests to work.

Here is the test:
```yaml
appId: APP_ID
env:
    today: ${new Date()}
---
- tapOn: .*Valitidity date.*
- evalScript: ${output.validityDate = new Date(today.getFullYear(), today.getMonth(), today.getDay() + 1)}
- inputText: ${output.validityDate}
- tapOn: "OK"
- tapOn: "Calculate"
- assertVisible: "Success"
```

Methods :
- getFullYear
- getMonth
- getDay
- getDate
- setDate

are not recognized. The test is crashing with the error: `TypeError: TypeError: Impossible de trouver la fonction getFullYear dans l'objet org.mozilla.javascript.NativeDate@537b32ef. (inline-script#1)}`

run command : 
```shell
$ maestro test flows/test.yaml
```

Environment
Maestro 1.18.5
macOS 12.5.1
