### ISSUE TITLE
Conditional flows should have a custom timeout

### ISSUE THREAD

**Issue by venkat2789** [mobile-dev-inc/maestro#684]
When running a conditional flow, the element deciding the flow may take time to load, and currently there doesn't seem to be a way to handle this. So conditional flows should have a custom timeout. Something like:
```
- runFlow:
    when:
      visible: Some Text
      timeout: 30000
    file: {reference to another yaml file}
```

We can either do the above or can support passing the optional parameter to the existing wait (but the above proposal may be neater approach). Something like
```
- extendedWaitUntil:
    visible: Element    
    timeout: 10000
    optional: true      
```

References:
https://maestro.mobile.dev/advanced/conditions
https://maestro.mobile.dev/advanced/wait
