### ISSUE TITLE
takescreenshot device is broken when multiple running devices detected.

### ISSUE THREAD

**Issue by shimastripe** [mobile-dev-inc/maestro#702]
## WHY

```
$ maestro -v
1.21.1
$ maestro test flow.yaml
iOS

[1] iPhone 14 - iOS 16.2
[2] iPhone 14 Pro - iOS 16.2
```

```yaml
appId: com.apple.Preferences
---
- launchApp
- takeScreenshot: MainScreen
```

The takeScreenshot command is detecting a wrong device, when I test the flow in multiple simulator devices running.
