### ISSUE TITLE
[Maestro Studio] Parsing nested commands fails

### ISSUE THREAD

**Issue by ArthurSav** [mobile-dev-inc/maestro#728]
Trying to run the following command on maestro studio fails.

```yaml
- repeat:
    times: 3
    commands:
        - swipe:
            start: "50%,80%"
            end: "50%,20%"
            duration: 100
```
[Parsing](https://github.com/mobile-dev-inc/maestro/blob/main/maestro-studio/server/src/main/java/maestro/studio/ReplService.kt#L179-L192) probably fails with nested commands

<img width="569" alt="Screenshot 2023-02-02 at 18 55 24" src="https://user-images.githubusercontent.com/2115575/216364464-33dd8c31-c439-4e3f-a3fa-95ea31c54d28.png">
