### ISSUE TITLE
New line character ignored for flow parameters

### ISSUE THREAD

**Issue by mugbug** [mobile-dev-inc/maestro#843]
I have two flow files:

```yaml
# reusable_flow.yaml
appId: app.id
---
- stopApp
- openLink: ${DEEPLINK_URL}
- assertVisible:
    text: ${EXPECTED_TEXT}
```

```yaml
# specific_flow.yaml
appId: app.id
---
- runFlow:
    file: deeplink_flow.yaml
    env:
      DEEPLINK_URL: https://google.com
      EXPECTED_TEXT: |-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        Mauris ut molestie eros.
```

If I run the `specific_flow.yaml`, it tries to assert the `"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Mauris ut molestie eros."` string instead of `"Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nMauris ut molestie eros."`.

I've also tried:

```yaml
# specific_flow.yaml
appId: app.id
---
- runFlow:
    file: deeplink_flow.yaml
    env:
      DEEPLINK_URL: https://google.com
      EXPECTED_TEXT: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nMauris ut molestie eros."
```

But the `\n` character was ignored as well.

And if I don't use the env vars, everything works as expected:

```yaml
# reusable_flow.yaml
appId: app.id
---
- stopApp
- openLink: ${DEEPLINK_URL}
- assertVisible:
    text: |-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        Mauris ut molestie eros.
```

**Comment by axelniklasson** [comment]
Hi @mugbug, thanks for reporting this. We'll take a look!

**Comment by axelniklasson** [comment]
@mugbug for now you can pass your multiline string with the `\n` character present and it should work

```
# specific_flow.yaml
appId: app.id
---
- runFlow:
    file: deeplink_flow.yaml
    env:
      DEEPLINK_URL: https://google.com
      EXPECTED_TEXT: Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nMauris ut molestie eros.
```

There is indeed a bug passing multiline strings as a parameter but I don't foresee this being prioritized very soon due to bandwidth so please use this workaround for now. Let me know if this works for you!
