### ISSUE TITLE
[Maestro Cloud] Proposal: Email Validation

### ISSUE THREAD

**Issue by igorsmotto** [mobile-dev-inc/maestro#844]
## Overview

This issue proposes a solution for testing end-to-end flows that include validating that emails are sent, and most importantly, extracting values out of the message to use elsewhere in the test. **We would like to hear your feedback.**

## Background

By simulating user interaction Maestro tries to replicate exactly how a user would normally use your App during a Flow execution.

There are, however, scenarios like _new user registration, password reset, user invite, and purchasing_, that require that the user interacts with an email sent to the user's email inbox. We consider these *advanced use cases*.  

One known workaround is to create a special user with relaxed security measures so that every action doesn't require leaving the App during test execution. Another method is to attempt to access the email inbox through the device's browser. Both have drawbacks: the former diminishes Maestro's coverage capacity, and the latter adds additional unwanted complexity, increasing flakiness probability.

## Proposal

To address this issue, we propose adding a way to both receive and search through emails in a Virtual Mailbox for Maestro Cloud. This will allow users to access their real emails during a flow execution, and most importantly, their content.

Since this problem is considered an *advanced use case*, this proposal leverages [Maestro's Javascript API](https://maestro.mobile.dev/advanced/javascript), adding a new auto-imported function to the Javascript Sandbox:

```tsx
function findEmail(email: Email, timeout?: number) => Email[];

interface Email {
    to?: string,
    from?: string,
    body?: string,
    subject?: string,
    date?: string
};
```

This function will poll the Mailbox's API querying for no longer than the timeout duration, as soon it finds one or more emails that match all arguments, it will return back their contents to be used.

At first, this proposal is only for users registered on Maestro Cloud, this is because there is a need to receive real emails from users and securely expose their contents for local executions of Maestro. 

## Usage

In this usage example, Maestro will execute a signup flow with a specific email address, and it will reuse this email address to find out if any email was sent to this address. 

```yaml
# Input email and complete sign-up
- inputText: "igor@example.com"
- tapOn: "Complete Sign-Up"
# As the sign-up is completed, app's backend will send an email to "igor@example.com"

# Now, Maestro will search through the mailbox to check if the email has arrived
- runScript: "email.js"

# Use content from email to navigate within the App (deep-link)
- openLink: ${output.acceptURL}
```

```jsx
// Search any email that was sent to igor@example.com
const emails = findEmail({
   to: "igor@example.com",
}, 3000);

// Get body of the email
const body = emails[0].body;

// Add to the output object the URL from the email's content 
const urlRegex = /(https?:\/\/[^\s]+)/g;
output.acceptURL = body.match(urlRegex)[0];
```
