### ISSUE TITLE
[BUG] scrollUntilVisible can't handle Ümlauts

### ISSUE THREAD

**Issue by marckrenn** [mobile-dev-inc/Maestro#857]
Given a button labeled `Antrag zurückziehen` below "the fold"

<img width="354" alt="Screenshot 2023-03-05 at 11 19 56" src="https://user-images.githubusercontent.com/2648540/222954614-92cc8624-f6a0-4754-8841-0460f4f4e1f9.png">

```yaml
- scrollUntilVisible:
    element:
      text: "Antrag zurückziehen"
```

won't even begin to scroll down.

```yaml
- scrollUntilVisible:
    element:
      text: "Antrag zuruckziehen"
```

Starts scrolling, but obviously times out eventually as it won't be able to find an element with `Antrag zuruckziehen`

Funnily enough
```yaml
- tapOn:
    text: "Antrag zurückziehen"
```
works just fine, so God knows what's going on 😅
