### ISSUE TITLE
switch between running apps

### ISSUE THREAD

**Issue by mzserroukh** [mobile-dev-inc/maestro#861]
It would be useful to have the ability to switch between apps and return to the last screen.
Using launchApp does open the app however the user is navigated back to the home screen of the app.

An example clicking a button in the app that launches a browser and then I want to return to app to validate something.

**Comment by reymalahay** [comment]
@mzserroukh have tried this:

when you launch the other app
```
- launchApp:
    appId: "the.id.of.app.to.launch"
    clearState: false
    # your automation commands here.
```

good luck,
rey malahay


> It would be useful to have the ability to switch between apps and return to the last screen. Using launchApp does open the app however the user is navigated back to the home screen of the app.
> 
> An example clicking a button in the app that launches a browser and then I want to return to app to validate something.
