### ISSUE TITLE
Flakyness when running flow on android arm64 emulator

### ISSUE THREAD

**Issue by Dambakk** [mobile-dev-inc/maestro#886]
When running a flow on an emulator maestro sometimes fail to assertVisibility of some text. 

I can see the text in Maestro Studio. When running the same flow several times in a row it sometimes fails and sometimes run successfully. The element is not present in the hierarchy (`maestro hierarchy`) if the test fails, and is present when it succeeds. 

There are no animations or loading state interfering with this test, and I've tried different ways of referencing, scrolling, and waiting for the element:

```
- scrollUntilVisible:
    element:
      text: "Gi tilbakemelding"
- extendedWaitUntil:
    visible:
       text: "Gi tilbakemelding"
    timeout: 10000
- assertVisible: 
    text: "Gi tilbakemelding"
- assertVisible: Gi tilbakemelding
``` 

I'm not experiencing any issues when running the same flow on a physical device.

Issue is discussed on slack: https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1678700923860579

Maestro version: 1.24.0
Emulator: API 32, arm64

**Comment by larryng** [comment]
I'm seeing a similar issue for a Compose lazy list that's populated after a delay. I've noticed that while the test is running, `maestro hierarchy` indeed _does not_ include the desired element, but almost immediately after the test fails `maestro hierarchy` _does_ include the element. I hypothesized that the rapid polling of the hierarchy was preventing it to update somehow, but adding a delay with exponential back-off of up to 2 seconds did not help.

Finally, I was able to workaround the issue in a very hacky way by something like this:
```yaml
- repeat:
    while:
      notVisible: ${desired_text}
    commands:
      - assertVisible:
          text: ${desired_text}
          optional: true
      - tapOn: "foobar"  # Whatever idempotent interaction just to trigger the hierarchy to update
# continue with the rest of the test
...
```
