### ISSUE TITLE
App Tracking Transparency Permission can't be set on iOS

### ISSUE THREAD

**Issue by jacobsapps** [mobile-dev-inc/maestro#906]
Hello 👋 

I'm fairly new to Maestro and absolutely loving it. Transitioning to this from Appium is like the difference between ARM Assembly and SwiftUI. Simply 🤯.

I've got a small teething issue which I think might be a bug on Maestro's side.

I can't set App Tracking Transparency permissions state in my flows. 

I'd expect to set it as such: 

```
appId: my.app.id com.gener8ads.wallet.debug
---
- launchApp:
    clearState: true
    permissions:
        usertracking: unset
- runFlow: subflows/my-subflow.yaml
```

I have some logic that shows the ATT permissions screen if ATT is not set, but this does not show up. However, when deleting the app from Simulator and running a real fresh install, it does show up. 

I've looked in your source code and in `maestro-ios/src/main/java/ios/simctl/Simctl.kt` the `usertracking` permission is listed in the list of all permissions, but it seems like it's not actually applied. 

Would really appreciate any help you can give, and happy to share more info as required!

Thanks,

Jacob
