### ISSUE TITLE
scrollUntilVisible with semanticsLabel

### ISSUE THREAD

**Issue by derohimat** [mobile-dev-inc/maestro#938]
Is that `scrollUntilVisible` support for Flutter `semanticsLabel` ?

I didn't found it on this docs https://maestro.mobile.dev/api-reference/commands/scrolluntilvisible

**Comment by igorsmotto** [comment]
Yes. It should. 
Docs for [Flutter can be found here](https://maestro.mobile.dev/platform-support/flutter). TL;DR: all commands that can query text will do first for semantic label.
Here is an example:
```
- scrollUntilVisible:
    element:
      text: "semantic-label-goes-here"
    direction: DOWN
```
