### ISSUE TITLE
Feature Request: scrollUntilPositioned

### ISSUE THREAD

**Issue by kunalverma25** [mobile-dev-inc/maestro#941]
Sometimes for testing purposes devs need to scroll a certain amount so that the desired element gets positioned at a certain point on the screen.

For Example:

There is an expandable element or something like a custom drop down.

In this case for testing the dev would want to scroll to a point where that element is at the top of the screen so when expanded or when the dropdown is opened, the rest of the elements are also rendered on the screen and can be acted upon.

This also could be an extension of scrollUntilVisible with a position parameter.

My proposal is to add a new command like this -

```
scrollUntilPositioned:
  element:
    id:
    other element params
  direction: UP|DOWN|RIGHT|LEFT
  position: TOP|BOTTOM|TRAILING|LEADING
  relativePosition: x%
  visibilityPercentage: x
```
