### ISSUE TITLE
Feature Request: Add support Enviroment Variables in runFlow

### ISSUE THREAD

**Issue by shigomany** [mobile-dev-inc/maestro#964]
### Description

Can I provide custom enviroment variables in my test file for **runFlow**?

My test file:
```yaml
appId: com.domain.app
tags:
  - single-file
---
- launchApp:
    clearState: true
    stopApp: true
- runFlow: ${FLOW}
```

Comand run:
```bash
maestro test flow/test.yaml -e FLOW=flow/otherTest.yaml
```

### Addition Info

I want to organize my tests in such a way that I don't have to write **launchApp** in each.
