### ISSUE TITLE
Running tapOn after hideKeyboard results in not tapping a button

### ISSUE THREAD

**Issue by pepyta** [mobile-dev-inc/maestro#993]
## Problem:
After the release of the 1.26.0 version, our tests started failing because tapping on a button right after hiding the keyboard caused it to not get actually tapped on. I think that the solution is that the `hideKeyboard` command should block the test run until the keyboard has finished the blocking of tapping other things on the screen.

## Environment:
- Android emulator
- API level: 29

## Example code:
```yaml
...
- tapOn:
    id: "name-field"
- inputText: ${NAME}
- tapOn:
    id: "email-field"
- inputText: ${EMAIL}
- tapOn:
    id: "password-field"
- inputText: ${PASSWORD}
- "hideKeyboard"
- tapOn:
    id: "register-button"
- assertVisible:
    text: "Sikeres regisztráció!" # <- Successful registration in Hungarian
...
```

## Versions:
- 1.25.0 ✅
- 1.26.0 ❌
- 1.26.1 ❌

## Example recording:
https://user-images.githubusercontent.com/23434629/231995958-a80125c5-add7-4bb0-a5e5-baac713c28d6.mp4
